/*
 * Lab-only interface text: option names and the labels of the preview chrome and
 * design-system sheets. None of it is website content.
 */

export type LabOption = "a" | "a2" | "b" | "c";

/** Route segment and short label of each option (A V2 refines A; A stays for comparison). */
export const labOptions: { key: LabOption; slug: string; short: string }[] = [
  { key: "a", slug: "modern-commerce-a", short: "A" },
  { key: "a2", slug: "modern-commerce-a-v2", short: "A V2" },
  { key: "b", slug: "modern-commerce-b", short: "B" },
  { key: "c", slug: "modern-commerce-c", short: "C" },
];

export const labCopy = {
  en: {
    lab: "Theme lab",
    preview: "Modern Commerce exploration",
    homepage: "Homepage",
    system: "Design system",
    note: "Light theme preview · noindex · links open the current site",
    noteA2: "Light and dark preview · noindex · links open the current site",
    darkLater: "Dark theme follows approval",
    optionNames: {
      a: "A · Clean Premium Commerce",
      a2: "A V2 · Clean Premium Commerce, refined",
      b: "B · Bold Industrial Commerce",
      c: "C · Minimal Luxury Commerce",
    },
    sheet: {
      palette: "Colour palette",
      paletteNote: "Orange is the anchor and the primary action; the supporting colours carry surfaces, icons, tags and states. Body text stays neutral.",
      type: "Typography",
      radius: "Radius",
      borders: "Borders",
      shadows: "Shadows",
      buttons: "Buttons",
      cards: "Cards",
      icons: "Icons, tags and badges",
      forms: "Form fields",
      display: "Display",
      heading: "Heading",
      body: "Body",
      label: "Label",
      english: "English",
      arabic: "Arabic",
      name: "Name",
      email: "Email",
      message: "Project details",
      required: "Required",
      helper: "Share drawings, quantities and timing.",
      states: { rest: "Rest", hover: "Hover", focus: "Focus", disabled: "Disabled" },
    },
    sheetA2: {
      cards: "Service, machinery and project cards",
      clients: "Client tiles",
      clientsNote: "Greyscale at rest; original colours on hover, on focus or with the switch. No counts, numbering or claims.",
      contact: "Contact blocks",
      motion: "Motion",
      motionNote:
        "One motion system: content fades and rises as it enters, cards lift 3 px, photos zoom 3.5 %, arrows move 3–4 px. Transform and opacity only. Only the background loops: the page ambient moves slowly all the time, in whole-pixel steps (see Background motion), and the hero plate's hot points breathe while the hero is on screen. With reduced motion every final state shows at once and nothing loops.",
      motionRows: [
        ["Quick", "180 ms", "Colour, borders, press feedback"],
        ["Standard", "320 ms", "Card lift, arrows, menus"],
        ["Reveal", "600 ms", "Section fade-ups, accent edges"],
        ["Entrance", "900 ms", "Hero entrance, photo settle"],
        ["Ease out", "cubic-bezier(0.22, 1, 0.36, 1)", "Everything that moves"],
        ["Ease in-out", "cubic-bezier(0.65, 0, 0.35, 1)", "Signature replays"],
        ["Hero plate", "≈ 5 s, once", "Pierce, trace and raster; never loops"],
        ["Background", "26 s · 28–32 s · 3.6 s", "The light and the colour field (always), the plate's hot points (on screen)"],
        ["Pointer", "0.24 per frame", "The ring trails the point (desktop mouse)"],
      ],
      motionHead: ["Token", "Value", "Use"],
      cut: "Signature · Laser cutting",
      cutNote:
        "The Laser Cutting page's nesting sheet, animated with the same geometry: nested steel parts, dimension rules and one part programmed in orange. The holes and the slot are cut first, as is usual in laser cutting, each from its pierce point and a short lead-in; then the outer contour from its lead-in, at a steady feed. A small hot point, a glow that trails the head and a heat tint that settles; no sparks. SVG and the Web Animations API only (transform, opacity, stroke-dashoffset). It plays once when half in view, replays on hover or keyboard focus of its card and never loops; with reduced motion or without JavaScript the finished sheet shows.",
      cutSteps: [
        "Sheet appears; one scan pass",
        "Nested parts draw in",
        "Cutting head activates",
        "Pierce point, then lead-in",
        "Holes and slot are cut first",
        "Outer contour from its lead-in",
        "Head parks; the heat settles",
      ],
      cutStates: {
        initial: "Initial state · sheet programmed, head ready",
        active: "Cutting · holes and slot done, outer contour under way",
        finished: "Finished · cut complete, head parked",
      },
      engrave: "Signature · Laser engraving",
      engraveNote:
        "The Laser Engraving page's brass plate, engraved by the laser with the same artwork: the crosshair moves to the start, then engraves the double border and corner marks, the block of lines and the guilloche rosette. Each groove is drawn twice, shadow and highlight, so it reads as cut into the metal. Light crosses the finished grooves and the laser switches off on its rest mark. A layout, not real text: no third-party brands, no part or serial numbers, no engraving photograph. It plays once when half in view and replays on hover or focus.",
      engraveSteps: [
        "Plate appears; the reflection settles",
        "Crosshair activates",
        "Laser moves to the start",
        "Double border and corner marks",
        "Engraved line block",
        "Rosette completes",
        "Light crosses the grooves",
        "Laser switches off",
      ],
      engraveStates: {
        initial: "Initial plate · crosshair ready",
        active: "Engraving · border and lines done, rosette under way",
        finished: "Completed engraving · laser at rest",
      },
      stills: "Still frames",
      replay: "Replay",
      reveal: "Loading and reveal",
      revealNote:
        "Content is visible without JavaScript. With it, sections rise 18 px as they enter, staggered by 50–90 ms, and photos open from a smaller frame while they settle. The hero runs its entrance on load, so nothing waits for scrolling.",
      replayReveal: "Replay the reveal",
      mobile: "Mobile components",
      mobileNote:
        "The real homepage at phone width: a full-height menu with large rows and the quote button always in reach, a 2 × 3 service strip, two-column mini cards, swipe rails for the pillars, machines and projects, and laser illustrations that play once.",
      mobileFrame: "Homepage preview at phone width",
      mobileRules: [
        "Tap targets of 44 px and more",
        "Get a Quote in the header and in the menu",
        "Swipe rails, never sideways page scroll",
        "Hover effects are extras: everything works by tap and keyboard",
      ],
      tokens: "Theme tokens",
      tokensNote:
        "Every colour is a semantic token on .lab-a2. The dark theme (html[data-theme=\"dark\"]) redefines the same names — surfaces, text, lines, tones, shadows, scrims — so no component changes.",
      tokenHead: ["Token", "Light", "Dark", "Role"],
      plate: "Signature · Hero plate",
      plateNote:
        "The website's approved hero plate, redrawn in A V2's language: a brushed steel plate with one laser-cut corner and the same geometry — 520 × 640, the eight-point star, the slot, four bolt holes and the perforation field — with its dimensions and measurement nodes. It rises onto its stage, the bolt holes are pierced, the laser traces the star and the slot at a steady feed and opens the perforation field row by row; the workshop glows through every opening. Orange nodes mark the measurement anchors and breathe softly while the hero is on screen. The mouse tilts the plate, moves its reflection and reads X / Y in plate millimetres; the readout counts the cuts. It plays once (about 5 s) and never loops; with reduced motion or without JavaScript the finished plate shows. SVG, CSS and the Web Animations API only.",
      plateSteps: [
        "Plate rises; dimensions draw in",
        "Four bolt holes pierced",
        "Star traced at a steady feed",
        "Slot traced",
        "Perforation field, row by row",
        "Nodes mark the anchors",
        "Readout: cut sequence 07/07",
      ],
      plateStates: {
        initial: "Initial · plate in place, dimensions drawn",
        active: "Cutting · the star under the laser",
        finished: "Finished · every opening cut",
      },
      backgrounds: "Backgrounds and surfaces",
      backgroundsNote:
        "Softer in both themes: a warm mist instead of white in the light theme, blue-charcoal instead of black in the dark theme. Each role is one token; the dark theme redefines the same names.",
      bgHead: ["Role", "Token", "Light", "Dark"],
      bgRoles: [
        "Base background",
        "Section background",
        "Recessed band",
        "Elevated surface (cards, panels)",
        "Muted surfaces (inner panels, tags)",
        "Accent surface (active, orange tint)",
        "Hero ambient layer",
        "Dark ambient layer (footer, contact)",
      ],
      light: "Light",
      dark: "Dark",
      themes: "Light and dark tones",
      themesNote:
        "The same components in both themes. Dark is blue-charcoal with lifted tones, never pure black; light is a warm mist with off-white cards, never pure white. Text meets AA on every surface.",
      contrast: "Contrast",
      contrastNote:
        "Measured ratios (WCAG 2.2 AA: 4.5:1 for text; 3:1 for large text, field borders, focus and meaningful icons). axe-core found no violations on the homepage or this sheet, in both languages and both themes, at 1440 and 390 px; text over photos and gradients was checked on the rendered pixels.",
      contrastHead: ["Pair", "Light", "Dark"],
      contrastRows: [
        "Headings on the page",
        "Body text on the page",
        "Body text on cards",
        "Secondary text, lowest surface",
        "Orange text links, lowest surface",
        "Tone text on its tint, lowest",
        "Primary button text",
        "Footer text",
        "Field border (3:1)",
        "Focus ring (3:1)",
        "Orange icons on their tint (3:1)",
        "Hero plate labels",
      ],
      cursor: "Pointer",
      cursorNote:
        "A small laser point with a precision ring that trails it slightly. Over links, buttons and cards the ring opens into an orange halo; over the hero plate it becomes a crosshair; pressing tightens it. Desktop mouse only: touch, pens, reduced motion and forced colours keep the system cursor, text fields keep the I-beam, and keyboard focus is untouched. Nothing depends on it.",
      cursorStates: ["At rest", "Link, button or card", "Hero plate", "Pressed", "On a dark band"],
      cursorRules: [
        "Desktop mouse only (hover and a fine pointer)",
        "System cursor for touch, pen, reduced motion and forced colours",
        "Text fields keep the I-beam; the lab bar keeps the arrow",
        "Transform only; the ring's loop stops once it catches up",
      ],
      bgMotion: "Background motion",
      bgMotionNote:
        "Visible, minimal and fast, always on behind every section. Two layers, both moved by the compositor in whole-pixel steps, a few changes a second. The surface — the page colour, the micro-dots and the colour (warm orange, steel blue and a touch of teal, three soft gradients) in one opaque layer — drifts and breathes. The one precision motif, a band of light made of orange dots on the same grid, crosses it every 26 s one dot column at a time and drifts with it, so the dots it passes light up. On screens without a GPU a sub-pixel move turns every frame into a filtered redraw, and every extra full-screen layer is one more to blend; whole pixels and a single opaque surface cost almost nothing, and nothing runs on the main thread. Text stays clear by construction: section sheets let about a tenth of the background through, cards stay opaque, and text on the open sections sits on a reading zone (page colour at 90 %, feathered), so the dots, the light and the strongest colour stay in the margins and gaps. Phones get a lighter version; with reduced motion it holds still. The frames below are the live layers held at a moment.",
      bgMotionFrames: ["Still · reduced motion", "8 s · the light enters", "11 s · mid-screen", "14 s · leaving"],
      bgMotionHead: ["Layer", "Light", "Dark", "Movement", "Timing", "Phones"],
      bgMotionRows: [
        ["Surface (layer 1): page colour, micro-dots, colour", "Dots ink 13 % · orange 12 %, steel 11 %, teal 7.5 %", "Dots steel-white 11.5 % · orange 10 %, steel 16 %, teal 7 %", "Drifts 48 × 24 px in 2 × 1 px steps; breathes between 0.7 and 1", "32 s and 28 s, back and forth; under two changes a second", "Colour at 70 %, no teal, 24 × 12 px"],
        ["Light (layer 2)", "Orange dots, 60 % at its centre", "Warm light dots, 50 % at its centre", "Crosses in whole dot columns (24 px), 864 px wide; drifts with the surface", "Every 26 s: crosses in 13 s, then rests off screen", "384 px wide"],
        ["Hero glows", "Orange 13 %, steel 10 %", "Orange 13 %, steel 15 %", "Still: the surface moves behind them", "—", "Same"],
      ],
      bgSurfaceHead: ["Surface", "Background seen"],
      bgSurfaceRows: [
        ["Hero", "All of it in the margins and around the plate, with the hero's own two still glows; the text column sits on a reading zone"],
        ["Open sections (about, projects, contact)", "All of it around the blocks; headings and paragraphs sit on a reading zone (page colour at 90 %, feathered)"],
        ["Section sheets (services, clients and compliance · machinery, industries)", "About 10 % · 8 % (light), 12 % · 10 % (dark)"],
        ["Cards and panels", "None: they stay opaque"],
        ["Dark contact panel", "Its own still micro-dots, 7 %"],
        ["Footer", "Its own still layer: micro-dots, a warm glow and a steel glow"],
      ],
      bgPerf: "Measured cost",
      bgPerfNote:
        "Headless Chromium without a GPU (software compositing, the worst case), the English homepage in the light theme; medians of five runs (scrolling at 1440 px: ten), the three builds taking turns. Scrolling: the whole page, top to bottom, in five seconds. Idle: five seconds with nothing touched. CPU is the share of one core.",
      bgPerfHead: ["Measure", "Pass 2 · still background", "Five layers · previous", "Now · two layers"],
      bgPerfRows: [
        ["Moving background layers", "1 (the hero glow)", "6", "2"],
        ["Scrolling at 1440 px · frames a second", "55.2", "43.4", "54.7"],
        ["Scrolling at 1440 px · frames over 50 ms, in ten scrolls", "7", "40", "15"],
        ["Scrolling at 390 px (phone) · frames a second", "60.2", "60.2", "60.2"],
        ["Idle mid-page, 1440 px · CPU", "0.6 %", "16 %", "6.8 %"],
        ["Idle mid-page, 1440 px · screen redraws a second", "0", "13", "5"],
        ["Idle at the top, 1440 px (with the plate's hot points) · CPU", "85 %", "103 %", "56 %"],
        ["Idle, 390 px (phone) · CPU at the top · mid-page", "14.6 % · 0.6 %", "24.2 % · 7.8 %", "7 % · 4.2 %"],
      ],
      layout: "Layout width",
      layoutNote:
        "The content column grows with the screen — min(1400 px, 92 vw) instead of a fixed 1240 px — and alternate sections are sheets inset 8–20 px from the screen edges, so large screens carry less empty margin without going edge to edge.",
      layoutHead: ["Screen", "Before · content / margin", "Now · content / margin"],
    },
  },
  ar: {
    lab: "مختبر التصميم",
    preview: "استكشاف الطابع التجاري الحديث",
    homepage: "الصفحة الرئيسية",
    system: "نظام التصميم",
    note: "معاينة بالوضع الفاتح · غير مفهرسة · الروابط تفتح الموقع الحالي",
    noteA2: "معاينة بالوضعين الفاتح والداكن · غير مفهرسة · الروابط تفتح الموقع الحالي",
    darkLater: "الوضع الداكن بعد الاعتماد",
    optionNames: {
      a: "A · تجاري راقٍ ونظيف",
      a2: "A V2 · تجاري راقٍ ونظيف، بنسخة مطوّرة",
      b: "B · تجاري صناعي جريء",
      c: "C · تجاري فاخر بسيط",
    },
    sheet: {
      palette: "لوحة الألوان",
      paletteNote: "البرتقالي هو اللون الأساسي ولون الإجراء الرئيسي، والألوان المساندة للأسطح والأيقونات والوسوم والحالات. يبقى نص الفقرات محايدًا.",
      type: "الخطوط",
      radius: "استدارة الزوايا",
      borders: "الحدود",
      shadows: "الظلال",
      buttons: "الأزرار",
      cards: "البطاقات",
      icons: "الأيقونات والوسوم والشارات",
      forms: "حقول النماذج",
      display: "عنوان رئيسي",
      heading: "عنوان",
      body: "نص",
      label: "تسمية",
      english: "الإنجليزية",
      arabic: "العربية",
      name: "الاسم",
      email: "البريد الإلكتروني",
      message: "تفاصيل المشروع",
      required: "مطلوب",
      helper: "أرفق المخططات والكميات والموعد المطلوب.",
      states: { rest: "عادي", hover: "تمرير", focus: "تركيز", disabled: "معطّل" },
    },
    sheetA2: {
      cards: "بطاقات الخدمات والمعدات والمشاريع",
      clients: "شعارات العملاء",
      clientsNote: "بالرمادي في الوضع العادي، وبألوانها الأصلية عند التمرير أو التركيز أو عبر المفتاح، دون أعداد أو ترقيم أو ادعاءات.",
      contact: "عناصر التواصل",
      motion: "الحركة",
      motionNote:
        "نظام حركة واحد: يظهر المحتوى بتلاشٍ وصعود خفيف عند دخوله الشاشة، وترتفع البطاقات 3 بكسل، وتقترب الصور بنسبة 3.5٪، وتتحرك الأسهم 3–4 بكسل. الحركة بالتحويل والشفافية فقط، ولا يتكرر إلا الخلفية: تتحرك أجواء الصفحة ببطء طوال الوقت بخطوات من بكسلات كاملة (انظر حركة الخلفية)، وتتوهج نقاط لوح الواجهة ما دامت الواجهة ظاهرة فقط. ومع خيار تقليل الحركة تظهر الحالة النهائية مباشرة ولا يتكرر شيء.",
      motionRows: [
        ["سريع", "180 ms", "الألوان والحدود والاستجابة عند الضغط"],
        ["قياسي", "320 ms", "ارتفاع البطاقات والأسهم والقوائم"],
        ["ظهور", "600 ms", "ظهور الأقسام والحواف الملوّنة"],
        ["دخول", "900 ms", "دخول الواجهة واستقرار الصورة"],
        ["تباطؤ في النهاية", "cubic-bezier(0.22, 1, 0.36, 1)", "كل ما يتحرك"],
        ["تسارع ثم تباطؤ", "cubic-bezier(0.65, 0, 0.35, 1)", "إعادة تشغيل التوقيع البصري"],
        ["لوح الواجهة", "≈ 5 ثوانٍ، مرة واحدة", "ثقب ورسم ومسح صفّي، دون تكرار"],
        ["الخلفية", "26 ثانية · 28–32 ثانية · 3.6 ثانية", "الضوء والحقل اللوني (دائمًا)، ونقاط اللوح المتوهجة (أثناء ظهورها)"],
        ["المؤشر", "0.24 لكل إطار", "تتبع الحلقة النقطة (فأرة سطح المكتب)"],
      ],
      motionHead: ["الرمز", "القيمة", "الاستخدام"],
      cut: "التوقيع البصري · القص بالليزر",
      cutNote:
        "لوح التعشيق في صفحة القص بالليزر، متحركًا بالهندسة نفسها: قطع فولاذية مرتّبة على اللوح، وخطوط أبعاد، وقطعة مبرمجة باللون البرتقالي. تُقص الثقوب والفتحة أولًا كما هو معتاد في القص بالليزر، كلٌّ من نقطة ثقبه عبر خط دخول قصير، ثم المحيط الخارجي من خط دخوله، بسرعة تغذية ثابتة. نقطة ساخنة صغيرة، وتوهّج يتبع الرأس، وأثر حراري يخبو تدريجيًا، دون شرر. رسم SVG وواجهة Web Animations فقط (التحويل والشفافية وstroke-dashoffset). يعمل مرة واحدة عند ظهور نصفه على الشاشة، ويُعاد عند التمرير على بطاقته أو التركيز عليها بلوحة المفاتيح، ولا يتكرر تلقائيًا؛ ومع تقليل الحركة أو دون JavaScript يظهر اللوح مكتمل القص.",
      cutSteps: [
        "ظهور اللوح ومرور خط المسح مرة واحدة",
        "رسم القطع المرتّبة على اللوح",
        "تفعيل رأس القص",
        "نقطة الثقب ثم خط الدخول",
        "قص الثقوب والفتحة أولًا",
        "قص المحيط الخارجي من خط الدخول",
        "عودة الرأس وخفوت الحرارة",
      ],
      cutStates: {
        initial: "الحالة الابتدائية · اللوح مبرمج والرأس جاهز",
        active: "أثناء القص · اكتملت الثقوب والفتحة والمحيط الخارجي قيد القص",
        finished: "القص المكتمل · عاد الرأس إلى موضعه",
      },
      engrave: "التوقيع البصري · الحفر بالليزر",
      engraveNote:
        "اللوح النحاسي في صفحة الحفر بالليزر، يحفره الليزر بالتصميم نفسه: ينتقل المؤشر إلى نقطة البداية، ثم يحفر الإطار المزدوج وعلامات الزوايا، فكتلة الأسطر، ثم الزخرفة الدائرية. يُرسم كل أخدود مرتين، ظلًا وإضاءة، فيبدو محفورًا في المعدن. ثم يعبر الضوء فوق الحفر المكتمل ويتوقف الليزر عند موضع سكونه. تخطيط لا نص حقيقي: لا علامات تجارية لجهات أخرى، ولا أرقام قطع أو أرقام تسلسلية، ولا صورة حفر. يعمل مرة واحدة عند ظهور نصفه على الشاشة، ويُعاد عند التمرير أو التركيز.",
      engraveSteps: [
        "ظهور اللوح واستقرار الانعكاس",
        "تفعيل مؤشر الليزر",
        "انتقال الليزر إلى نقطة البداية",
        "الإطار المزدوج وعلامات الزوايا",
        "كتلة الأسطر المحفورة",
        "اكتمال الزخرفة الدائرية",
        "عبور الضوء فوق الحفر",
        "إيقاف الليزر",
      ],
      engraveStates: {
        initial: "اللوح قبل الحفر · المؤشر جاهز",
        active: "أثناء الحفر · اكتمل الإطار والأسطر والزخرفة قيد التنفيذ",
        finished: "الحفر المكتمل · الليزر في وضع السكون",
      },
      stills: "لقطات ثابتة",
      replay: "إعادة التشغيل",
      reveal: "التحميل والظهور",
      revealNote:
        "المحتوى ظاهر دون JavaScript. ومعه تصعد الأقسام 18 بكسل عند دخولها الشاشة بفارق 50–90 جزءًا من الثانية، وتنفتح الصور من إطار أصغر وهي تستقر. وتبدأ حركة الواجهة عند التحميل، فلا ينتظر أي جزء التمرير.",
      replayReveal: "إعادة الظهور",
      mobile: "مكوّنات الجوال",
      mobileNote:
        "الصفحة الرئيسية الفعلية بعرض الجوال: قائمة بكامل الارتفاع بصفوف كبيرة وزر طلب عرض السعر في المتناول دائمًا، وشريط خدمات 2 × 3، وبطاقات مصغّرة في عمودين، وشرائح أفقية لمزايا رواسي والمعدات والمشاريع، ورسوم ليزر تعمل مرة واحدة.",
      mobileFrame: "معاينة الصفحة الرئيسية بعرض الجوال",
      mobileRules: [
        "مساحات لمس 44 بكسل فأكثر",
        "زر طلب عرض السعر في الترويسة وفي القائمة",
        "شرائح أفقية دون تمرير أفقي للصفحة",
        "تأثيرات التمرير إضافة فقط: كل شيء يعمل باللمس ولوحة المفاتيح",
      ],
      tokens: "رموز المظهر",
      tokensNote:
        "كل لون رمز دلالي على ‎.lab-a2، ويعيد الوضع الداكن ‎(html[data-theme=\"dark\"]) تعريف الأسماء نفسها — الأسطح والنصوص والحدود والألوان المساندة والظلال والتظليل — دون تغيير أي مكوّن.",
      tokenHead: ["الرمز", "الفاتح", "الداكن", "الدور"],
      plate: "التوقيع البصري · لوح الواجهة",
      plateNote:
        "لوح الواجهة المعتمد في الموقع، بإعادة رسم تناسب لغة A V2: لوح فولاذي مصقول بزاوية مشطوفة بالليزر وبالهندسة نفسها — 520 × 640، والنجمة الثمانية، والفتحة، وأربعة ثقوب تثبيت، وحقل الثقوب الدقيقة — مع أبعاده ونقاط القياس. يرتفع اللوح إلى منصته، ثم تُثقب ثقوب التثبيت، ويرسم الليزر النجمة والفتحة بسرعة تغذية ثابتة، ويفتح حقل الثقوب صفًّا بعد صف، فتظهر الورشة متوهجة عبر كل فتحة. تحدد نقاط برتقالية مواضع القياس، وتنبض بهدوء ما دامت الواجهة ظاهرة. وتُميل الفأرة اللوح وتحرّك انعكاسه وتعرض الإحداثيين X / Y بالمليمتر، ويعدّ المؤشر عمليات القص. يعمل مرة واحدة (نحو 5 ثوانٍ) ولا يتكرر؛ ومع تقليل الحركة أو دون JavaScript يظهر اللوح مكتملًا. رسم SVG وCSS وواجهة Web Animations فقط.",
      plateSteps: [
        "ارتفاع اللوح ورسم الأبعاد",
        "ثقب فتحات التثبيت الأربع",
        "رسم النجمة بسرعة تغذية ثابتة",
        "رسم الفتحة",
        "حقل الثقوب صفًّا بعد صف",
        "تحديد نقاط القياس",
        "المؤشر: تسلسل القص 07/07",
      ],
      plateStates: {
        initial: "الحالة الابتدائية · اللوح في موضعه والأبعاد مرسومة",
        active: "أثناء القص · النجمة تحت الليزر",
        finished: "القص المكتمل · جميع الفتحات مقصوصة",
      },
      backgrounds: "الخلفيات والأسطح",
      backgroundsNote:
        "أنعم في الوضعين: ضباب دافئ بدل الأبيض في الوضع الفاتح، ورمادي فحمي مائل إلى الأزرق بدل الأسود في الوضع الداكن. لكل دور رمز واحد، ويعيد الوضع الداكن تعريف الأسماء نفسها.",
      bgHead: ["الدور", "الرمز", "الفاتح", "الداكن"],
      bgRoles: [
        "خلفية الصفحة الأساسية",
        "خلفية الأقسام",
        "شريط غائر",
        "سطح بارز (البطاقات واللوحات)",
        "أسطح هادئة (لوحات داخلية ووسوم)",
        "سطح التمييز (الحالة النشطة وتدرّج البرتقالي)",
        "طبقة أجواء الواجهة",
        "طبقة الأجواء الداكنة (التذييل والتواصل)",
      ],
      light: "الفاتح",
      dark: "الداكن",
      themes: "درجات الوضعين الفاتح والداكن",
      themesNote:
        "المكوّنات نفسها في الوضعين. الداكن رمادي فحمي مائل إلى الأزرق بألوان مساندة أفتح، دون أسود خالص؛ والفاتح ضباب دافئ ببطاقات بيضاء مكسورة، دون أبيض خالص. والنص يحقق مستوى AA على كل الأسطح.",
      contrast: "التباين",
      contrastNote:
        "نسب مقيسة (WCAG 2.2 بمستوى AA: ‏4.5:1 للنص، و3:1 للنص الكبير وحدود الحقول ومؤشر التركيز والأيقونات ذات الدلالة). لم تجد أداة axe-core أي مخالفة في الصفحة الرئيسية ولا في هذه الصفحة، باللغتين وفي الوضعين، بعرض 1440 و390 بكسل؛ وجرى التحقق من النص فوق الصور والتدرجات على البكسلات المعروضة.",
      contrastHead: ["الزوج", "الفاتح", "الداكن"],
      contrastRows: [
        "العناوين على الصفحة",
        "نص الفقرات على الصفحة",
        "نص الفقرات على البطاقات",
        "النص الثانوي على أضعف سطح",
        "روابط النص البرتقالية على أضعف سطح",
        "نص اللون المساند على تدرّجه، الأدنى",
        "نص الزر الرئيسي",
        "نص التذييل",
        "حدود الحقول (3:1)",
        "مؤشر التركيز (3:1)",
        "الأيقونات البرتقالية على تدرّجها (3:1)",
        "تسميات لوح الواجهة",
      ],
      cursor: "المؤشر",
      cursorNote:
        "نقطة ليزر صغيرة تتبعها حلقة دقة بتأخر طفيف. فوق الروابط والأزرار والبطاقات تتسع الحلقة إلى هالة برتقالية، وفوق لوح الواجهة تصبح علامة تصويب، وتضيق عند الضغط. للفأرة على أجهزة سطح المكتب فقط: يبقى مؤشر النظام مع اللمس والقلم وتقليل الحركة والألوان القسرية، وتحتفظ حقول النص بمؤشر الكتابة، ولا يتأثر التنقل بلوحة المفاتيح. ولا يعتمد عليه أي شيء.",
      cursorStates: ["في السكون", "رابط أو زر أو بطاقة", "لوح الواجهة", "عند الضغط", "على شريط داكن"],
      cursorRules: [
        "للفأرة على سطح المكتب فقط (تمرير ومؤشر دقيق)",
        "مؤشر النظام مع اللمس والقلم وتقليل الحركة والألوان القسرية",
        "حقول النص تحتفظ بمؤشر الكتابة، وشريط المختبر بالسهم",
        "بالتحويل فقط، وتتوقف حركة الحلقة حين تلحق بالنقطة",
      ],
      bgMotion: "حركة الخلفية",
      bgMotionNote:
        "خلفية ظاهرة وهادئة وخفيفة، تعمل دائمًا خلف كل الأقسام. طبقتان فقط يحرّكهما مُركّب المتصفح بخطوات من بكسلات كاملة، بضع مرات في الثانية. السطح — لون الصفحة والنقاط الدقيقة واللون (برتقالي دافئ وأزرق فولاذي ولمسة من الأخضر المزرق في ثلاثة تدرجات ناعمة) في طبقة واحدة معتمة — ينساب ويتنفس ببطء. وعنصر الدقة الوحيد، شريط ضوء من نقاط برتقالية على الشبكة نفسها، يعبره كل 26 ثانية عمودًا بعد عمود وينساب معه، فتضيء النقاط التي يمر بها. على الأجهزة التي تعمل دون معالج رسوميات تجعل الحركة بأجزاء من البكسل كل إطار إعادة رسم كاملة، وكل طبقة إضافية بملء الشاشة طبقة أخرى يجب دمجها؛ أما البكسلات الكاملة والسطح المعتم الواحد فتكاد لا تكلّف شيئًا، ولا يعمل شيء منها على الخيط الرئيسي. ويبقى النص واضحًا بالتصميم نفسه: تُظهر ألواح الأقسام نحو عُشر الخلفية، وتبقى البطاقات معتمة، ويقع النص في الأقسام المفتوحة على منطقة قراءة (لون الصفحة بنسبة 90٪ بحواف متلاشية)، فتبقى النقاط والضوء وأقوى الألوان في الهوامش والفراغات. وللهواتف نسخة أخف، ومع تقليل الحركة تثبت الخلفية. الإطارات أدناه هي الطبقات الحية نفسها موقوفة عند لحظة.",
      bgMotionFrames: ["ثابتة · مع تقليل الحركة", "8 ثوانٍ · يدخل الضوء", "11 ثانية · منتصف الشاشة", "14 ثانية · يغادر"],
      bgMotionHead: ["الطبقة", "الفاتح", "الداكن", "الحركة", "التوقيت", "الهواتف"],
      bgMotionRows: [
        ["السطح (الطبقة 1): لون الصفحة والنقاط الدقيقة واللون", "النقاط حبر 13٪ · برتقالي 12٪، فولاذي 11٪، أخضر مزرق 7.5٪", "النقاط أبيض فولاذي 11.5٪ · برتقالي 10٪، فولاذي 16٪، أخضر مزرق 7٪", "ينساب 48 × 24 بكسل بخطوات 2 × 1 بكسل، ويتنفس بين 0.7 و1", "32 و28 ثانية ذهابًا وإيابًا، بأقل من تغييرين في الثانية", "اللون بنسبة 70٪ دون الأخضر المزرق، 24 × 12 بكسل"],
        ["الضوء (الطبقة 2)", "نقاط برتقالية، 60٪ في منتصفه", "نقاط ضوء دافئ، 50٪ في منتصفه", "يعبر بأعمدة نقاط كاملة (24 بكسل) بعرض 864 بكسل، وينساب مع السطح", "كل 26 ثانية: يعبر في 13 ثانية ثم يستقر خارج الشاشة", "بعرض 384 بكسل"],
        ["توهج الواجهة", "برتقالي 13٪، فولاذي 10٪", "برتقالي 13٪، فولاذي 15٪", "ثابت: يتحرك السطح خلفه", "—", "كما هو"],
      ],
      bgSurfaceHead: ["السطح", "ما يظهر من الخلفية"],
      bgSurfaceRows: [
        ["الواجهة", "كاملة في الهوامش وحول اللوح، مع توهجين ثابتين خاصين بها؛ ويقع عمود النص على منطقة قراءة"],
        ["الأقسام المفتوحة (من نحن، المشاريع، التواصل)", "كاملة حول الكتل؛ وتقع العناوين والفقرات على منطقة قراءة (لون الصفحة بنسبة 90٪ بحواف متلاشية)"],
        ["ألواح الأقسام (الخدمات، والعملاء والامتثال · المعدات والقطاعات)", "نحو 10٪ · 8٪ (الفاتح)، و12٪ · 10٪ (الداكن)"],
        ["البطاقات واللوحات", "لا شيء: تبقى معتمة"],
        ["لوحة التواصل الداكنة", "نقاطها الدقيقة الثابتة، 7٪"],
        ["التذييل", "طبقته الثابتة الخاصة: نقاط دقيقة وتوهج دافئ وآخر فولاذي"],
      ],
      bgPerf: "التكلفة المقيسة",
      bgPerfNote:
        "متصفح Chromium دون واجهة ودون معالج رسوميات (تركيب برمجي، وهو أسوأ الحالات)، على الصفحة الرئيسية الإنجليزية في الوضع الفاتح؛ القيم وسيط خمس جولات (وعشر جولات للتمرير بعرض 1440 بكسل) تتناوب فيها النسخ الثلاث. التمرير: الصفحة كاملة من أعلاها إلى أسفلها خلال خمس ثوانٍ. السكون: خمس ثوانٍ دون أي تفاعل. ونسبة المعالج محسوبة من نواة واحدة.",
      bgPerfHead: ["القياس", "المرحلة الثانية · خلفية ثابتة", "خمس طبقات · السابقة", "الآن · طبقتان"],
      bgPerfRows: [
        ["طبقات الخلفية المتحركة", "1 (توهج الواجهة)", "6", "2"],
        ["التمرير بعرض 1440 بكسل · إطار في الثانية", "55.2", "43.4", "54.7"],
        ["التمرير بعرض 1440 بكسل · إطارات تجاوزت 50 ms في عشر مرات تمرير", "7", "40", "15"],
        ["التمرير بعرض 390 بكسل (هاتف) · إطار في الثانية", "60.2", "60.2", "60.2"],
        ["السكون في منتصف الصفحة، 1440 بكسل · المعالج", "0.6 %", "16 %", "6.8 %"],
        ["السكون في منتصف الصفحة، 1440 بكسل · مرات إعادة الرسم في الثانية", "0", "13", "5"],
        ["السكون أعلى الصفحة، 1440 بكسل (مع نقاط اللوح المتوهجة) · المعالج", "85 %", "103 %", "56 %"],
        ["السكون، 390 بكسل (هاتف) · المعالج أعلى الصفحة · في منتصفها", "14.6 % · 0.6 %", "24.2 % · 7.8 %", "7 % · 4.2 %"],
      ],
      layout: "عرض التخطيط",
      layoutNote:
        "يتسع عمود المحتوى مع الشاشة — ‎min(1400 px, 92 vw)‎ بدل 1240 بكسل ثابتة — وتصبح الأقسام المتبادلة ألواحًا تبعد 8–20 بكسل عن حواف الشاشة، فتقل المساحات الفارغة على الشاشات الكبيرة دون أن يمتد المحتوى من الحافة إلى الحافة.",
      layoutHead: ["الشاشة", "سابقًا · المحتوى / الهامش", "الآن · المحتوى / الهامش"],
    },
  },
} as const;
