/*
 * Lab-only interface text: option names and the labels of the preview chrome and
 * design-system sheets. None of it is website content.
 */

export type LabOption = "a" | "a2" | "b" | "c";

/** Route segment and short label of each option (A V2 refines A; A stays for comparison). */
export const labOptions: { key: LabOption; slug: string; short: string }[] = [
  { key: "a", slug: "modern-commerce-a", short: "A" },
  { key: "a2", slug: "modern-commerce-a-v2", short: "A V2" },
  { key: "b", slug: "modern-commerce-b", short: "B" },
  { key: "c", slug: "modern-commerce-c", short: "C" },
];

export const labCopy = {
  en: {
    lab: "Theme lab",
    preview: "Modern Commerce exploration",
    homepage: "Homepage",
    system: "Design system",
    note: "Light theme preview · noindex · links open the current site",
    darkLater: "Dark theme follows approval",
    optionNames: {
      a: "A · Clean Premium Commerce",
      a2: "A V2 · Clean Premium Commerce, refined",
      b: "B · Bold Industrial Commerce",
      c: "C · Minimal Luxury Commerce",
    },
    sheet: {
      palette: "Colour palette",
      paletteNote: "Orange is the anchor and the primary action; the supporting colours carry surfaces, icons, tags and states. Body text stays neutral.",
      type: "Typography",
      radius: "Radius",
      borders: "Borders",
      shadows: "Shadows",
      buttons: "Buttons",
      cards: "Cards",
      icons: "Icons, tags and badges",
      forms: "Form fields",
      display: "Display",
      heading: "Heading",
      body: "Body",
      label: "Label",
      english: "English",
      arabic: "Arabic",
      name: "Name",
      email: "Email",
      message: "Project details",
      required: "Required",
      helper: "Share drawings, quantities and timing.",
      states: { rest: "Rest", hover: "Hover", focus: "Focus", disabled: "Disabled" },
    },
    sheetA2: {
      cards: "Service, machinery and project cards",
      clients: "Client tiles",
      clientsNote: "Greyscale at rest; original colours on hover, on focus or with the switch. No counts, numbering or claims.",
      contact: "Contact blocks",
      motion: "Motion",
      motionNote:
        "One motion system: content fades and rises as it enters, cards lift 3 px, photos zoom 3.5 %, arrows move 3–4 px. Transform and opacity only. Nothing loops except the hero light, which pauses off screen. With reduced motion every final state shows at once.",
      motionRows: [
        ["Quick", "180 ms", "Colour, borders, press feedback"],
        ["Standard", "320 ms", "Card lift, arrows, menus"],
        ["Reveal", "600 ms", "Section fade-ups, accent edges"],
        ["Entrance", "900 ms", "Hero entrance, photo settle"],
        ["Ease out", "cubic-bezier(0.22, 1, 0.36, 1)", "Everything that moves"],
        ["Ease in-out", "cubic-bezier(0.65, 0, 0.35, 1)", "Signature replays"],
      ],
      motionHead: ["Token", "Value", "Use"],
      cut: "Signature · Laser cutting",
      cutNote:
        "The Laser Cutting page's nesting sheet, animated with the same geometry: nested steel parts, dimension rules and one part programmed in orange. The holes and the slot are cut first, as is usual in laser cutting, each from its pierce point and a short lead-in; then the outer contour from its lead-in, at a steady feed. A small hot point, a glow that trails the head and a heat tint that settles; no sparks. SVG and the Web Animations API only (transform, opacity, stroke-dashoffset). It plays once when half in view, replays on hover or keyboard focus of its card and never loops; with reduced motion or without JavaScript the finished sheet shows.",
      cutSteps: [
        "Sheet appears; one scan pass",
        "Nested parts draw in",
        "Cutting head activates",
        "Pierce point, then lead-in",
        "Holes and slot are cut first",
        "Outer contour from its lead-in",
        "Head parks; the heat settles",
      ],
      cutStates: {
        initial: "Initial state · sheet programmed, head ready",
        active: "Cutting · holes and slot done, outer contour under way",
        finished: "Finished · cut complete, head parked",
      },
      engrave: "Signature · Laser engraving",
      engraveNote:
        "The Laser Engraving page's brass plate, engraved by the laser with the same artwork: the crosshair moves to the start, then engraves the double border and corner marks, the block of lines and the guilloche rosette. Each groove is drawn twice, shadow and highlight, so it reads as cut into the metal. Light crosses the finished grooves and the laser switches off on its rest mark. A layout, not real text: no third-party brands, no part or serial numbers, no engraving photograph. It plays once when half in view and replays on hover or focus.",
      engraveSteps: [
        "Plate appears; the reflection settles",
        "Crosshair activates",
        "Laser moves to the start",
        "Double border and corner marks",
        "Engraved line block",
        "Rosette completes",
        "Light crosses the grooves",
        "Laser switches off",
      ],
      engraveStates: {
        initial: "Initial plate · crosshair ready",
        active: "Engraving · border and lines done, rosette under way",
        finished: "Completed engraving · laser at rest",
      },
      stills: "Still frames",
      replay: "Replay",
      reveal: "Loading and reveal",
      revealNote:
        "Content is visible without JavaScript. With it, sections rise 18 px as they enter, staggered by 50–90 ms, and photos open from a smaller frame while they settle. The hero runs its entrance on load, so nothing waits for scrolling.",
      replayReveal: "Replay the reveal",
      mobile: "Mobile components",
      mobileNote:
        "The real homepage at phone width: a full-height menu with large rows and the quote button always in reach, a 2 × 3 service strip, two-column mini cards, swipe rails for the pillars, machines and projects, and laser illustrations that play once.",
      mobileFrame: "Homepage preview at phone width",
      mobileRules: [
        "Tap targets of 44 px and more",
        "Get a Quote in the header and in the menu",
        "Swipe rails, never sideways page scroll",
        "Hover effects are extras: everything works by tap and keyboard",
      ],
      tokens: "Theme tokens",
      tokensNote:
        "Every colour is a semantic token on .lab-a2. The dark theme follows approval: it redefines the same names (surfaces, text, lines, tones, shadows, scrims), so no component changes.",
      tokenHead: ["Token", "Light", "Role"],
    },
  },
  ar: {
    lab: "مختبر التصميم",
    preview: "استكشاف الطابع التجاري الحديث",
    homepage: "الصفحة الرئيسية",
    system: "نظام التصميم",
    note: "معاينة بالوضع الفاتح · غير مفهرسة · الروابط تفتح الموقع الحالي",
    darkLater: "الوضع الداكن بعد الاعتماد",
    optionNames: {
      a: "A · تجاري راقٍ ونظيف",
      a2: "A V2 · تجاري راقٍ ونظيف، بنسخة مطوّرة",
      b: "B · تجاري صناعي جريء",
      c: "C · تجاري فاخر بسيط",
    },
    sheet: {
      palette: "لوحة الألوان",
      paletteNote: "البرتقالي هو اللون الأساسي ولون الإجراء الرئيسي، والألوان المساندة للأسطح والأيقونات والوسوم والحالات. يبقى نص الفقرات محايدًا.",
      type: "الخطوط",
      radius: "استدارة الزوايا",
      borders: "الحدود",
      shadows: "الظلال",
      buttons: "الأزرار",
      cards: "البطاقات",
      icons: "الأيقونات والوسوم والشارات",
      forms: "حقول النماذج",
      display: "عنوان رئيسي",
      heading: "عنوان",
      body: "نص",
      label: "تسمية",
      english: "الإنجليزية",
      arabic: "العربية",
      name: "الاسم",
      email: "البريد الإلكتروني",
      message: "تفاصيل المشروع",
      required: "مطلوب",
      helper: "أرفق المخططات والكميات والموعد المطلوب.",
      states: { rest: "عادي", hover: "تمرير", focus: "تركيز", disabled: "معطّل" },
    },
    sheetA2: {
      cards: "بطاقات الخدمات والمعدات والمشاريع",
      clients: "شعارات العملاء",
      clientsNote: "بالرمادي في الوضع العادي، وبألوانها الأصلية عند التمرير أو التركيز أو عبر المفتاح، دون أعداد أو ترقيم أو ادعاءات.",
      contact: "عناصر التواصل",
      motion: "الحركة",
      motionNote:
        "نظام حركة واحد: يظهر المحتوى بتلاشٍ وصعود خفيف عند دخوله الشاشة، وترتفع البطاقات 3 بكسل، وتقترب الصور بنسبة 3.5٪، وتتحرك الأسهم 3–4 بكسل. الحركة بالتحويل والشفافية فقط، ولا يتكرر شيء سوى ضوء الواجهة الذي يتوقف خارج الشاشة. ومع خيار تقليل الحركة تظهر الحالة النهائية مباشرة.",
      motionRows: [
        ["سريع", "180 ms", "الألوان والحدود والاستجابة عند الضغط"],
        ["قياسي", "320 ms", "ارتفاع البطاقات والأسهم والقوائم"],
        ["ظهور", "600 ms", "ظهور الأقسام والحواف الملوّنة"],
        ["دخول", "900 ms", "دخول الواجهة واستقرار الصورة"],
        ["تباطؤ في النهاية", "cubic-bezier(0.22, 1, 0.36, 1)", "كل ما يتحرك"],
        ["تسارع ثم تباطؤ", "cubic-bezier(0.65, 0, 0.35, 1)", "إعادة تشغيل التوقيع البصري"],
      ],
      motionHead: ["الرمز", "القيمة", "الاستخدام"],
      cut: "التوقيع البصري · القص بالليزر",
      cutNote:
        "لوح التعشيق في صفحة القص بالليزر، متحركًا بالهندسة نفسها: قطع فولاذية مرتّبة على اللوح، وخطوط أبعاد، وقطعة مبرمجة باللون البرتقالي. تُقص الثقوب والفتحة أولًا كما هو معتاد في القص بالليزر، كلٌّ من نقطة ثقبه عبر خط دخول قصير، ثم المحيط الخارجي من خط دخوله، بسرعة تغذية ثابتة. نقطة ساخنة صغيرة، وتوهّج يتبع الرأس، وأثر حراري يخبو تدريجيًا، دون شرر. رسم SVG وواجهة Web Animations فقط (التحويل والشفافية وstroke-dashoffset). يعمل مرة واحدة عند ظهور نصفه على الشاشة، ويُعاد عند التمرير على بطاقته أو التركيز عليها بلوحة المفاتيح، ولا يتكرر تلقائيًا؛ ومع تقليل الحركة أو دون JavaScript يظهر اللوح مكتمل القص.",
      cutSteps: [
        "ظهور اللوح ومرور خط المسح مرة واحدة",
        "رسم القطع المرتّبة على اللوح",
        "تفعيل رأس القص",
        "نقطة الثقب ثم خط الدخول",
        "قص الثقوب والفتحة أولًا",
        "قص المحيط الخارجي من خط الدخول",
        "عودة الرأس وخفوت الحرارة",
      ],
      cutStates: {
        initial: "الحالة الابتدائية · اللوح مبرمج والرأس جاهز",
        active: "أثناء القص · اكتملت الثقوب والفتحة والمحيط الخارجي قيد القص",
        finished: "القص المكتمل · عاد الرأس إلى موضعه",
      },
      engrave: "التوقيع البصري · الحفر بالليزر",
      engraveNote:
        "اللوح النحاسي في صفحة الحفر بالليزر، يحفره الليزر بالتصميم نفسه: ينتقل المؤشر إلى نقطة البداية، ثم يحفر الإطار المزدوج وعلامات الزوايا، فكتلة الأسطر، ثم الزخرفة الدائرية. يُرسم كل أخدود مرتين، ظلًا وإضاءة، فيبدو محفورًا في المعدن. ثم يعبر الضوء فوق الحفر المكتمل ويتوقف الليزر عند موضع سكونه. تخطيط لا نص حقيقي: لا علامات تجارية لجهات أخرى، ولا أرقام قطع أو أرقام تسلسلية، ولا صورة حفر. يعمل مرة واحدة عند ظهور نصفه على الشاشة، ويُعاد عند التمرير أو التركيز.",
      engraveSteps: [
        "ظهور اللوح واستقرار الانعكاس",
        "تفعيل مؤشر الليزر",
        "انتقال الليزر إلى نقطة البداية",
        "الإطار المزدوج وعلامات الزوايا",
        "كتلة الأسطر المحفورة",
        "اكتمال الزخرفة الدائرية",
        "عبور الضوء فوق الحفر",
        "إيقاف الليزر",
      ],
      engraveStates: {
        initial: "اللوح قبل الحفر · المؤشر جاهز",
        active: "أثناء الحفر · اكتمل الإطار والأسطر والزخرفة قيد التنفيذ",
        finished: "الحفر المكتمل · الليزر في وضع السكون",
      },
      stills: "لقطات ثابتة",
      replay: "إعادة التشغيل",
      reveal: "التحميل والظهور",
      revealNote:
        "المحتوى ظاهر دون JavaScript. ومعه تصعد الأقسام 18 بكسل عند دخولها الشاشة بفارق 50–90 جزءًا من الثانية، وتنفتح الصور من إطار أصغر وهي تستقر. وتبدأ حركة الواجهة عند التحميل، فلا ينتظر أي جزء التمرير.",
      replayReveal: "إعادة الظهور",
      mobile: "مكوّنات الجوال",
      mobileNote:
        "الصفحة الرئيسية الفعلية بعرض الجوال: قائمة بكامل الارتفاع بصفوف كبيرة وزر طلب عرض السعر في المتناول دائمًا، وشريط خدمات 2 × 3، وبطاقات مصغّرة في عمودين، وشرائح أفقية لمزايا رواسي والمعدات والمشاريع، ورسوم ليزر تعمل مرة واحدة.",
      mobileFrame: "معاينة الصفحة الرئيسية بعرض الجوال",
      mobileRules: [
        "مساحات لمس 44 بكسل فأكثر",
        "زر طلب عرض السعر في الترويسة وفي القائمة",
        "شرائح أفقية دون تمرير أفقي للصفحة",
        "تأثيرات التمرير إضافة فقط: كل شيء يعمل باللمس ولوحة المفاتيح",
      ],
      tokens: "رموز المظهر",
      tokensNote:
        "كل لون رمز دلالي على ‎.lab-a2. ويأتي الوضع الداكن بعد الاعتماد بإعادة تعريف الأسماء نفسها (الأسطح والنصوص والحدود والألوان المساندة والظلال والتظليل)، دون تغيير أي مكوّن.",
      tokenHead: ["الرمز", "الفاتح", "الدور"],
    },
  },
} as const;
