// AUTO-GENERATED by scripts/extract-profile-assets.py — do not edit by hand.
// Intrinsic sizes + blur placeholders for every extracted asset.

export const mediaRegistry = {
  "certificates/commercial-activity-licence": {
    "src": "/media/certificates/commercial-activity-licence.webp",
    "width": 1100,
    "height": 1558,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoLABAAA4BaJZQCw7EUo3y2fqcAAP71AoIirhJdEbEwIeQWhuc9FerNJKRBGAAA"
  },
  "certificates/commercial-activity-licence-thumb": {
    "src": "/media/certificates/commercial-activity-licence-thumb.webp",
    "width": 560,
    "height": 793,
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoLABAAA4BaJZQCw7EUqqGXoRsAAP71Aq8YyR82dRW/rrVWVGoj9qR0aXzwvgU4KBgAAA=="
  },
  "certificates/commercial-registration-ar": {
    "src": "/media/certificates/commercial-registration-ar.webp",
    "width": 1100,
    "height": 778,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAsAA4BaJagC7AEQN/apa8vJgAD+9iUkGZNOgsZ/q2OYEvb9qgbKEK9I/oH9bNy48KfgnaASaZ2KWcGYdmuW22Yr7B9AAAA="
  },
  "certificates/commercial-registration-ar-thumb": {
    "src": "/media/certificates/commercial-registration-ar-thumb.webp",
    "width": 560,
    "height": 396,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAsAA4BaJagC7AEQN/apSMxMAAD+9iUkGZNOgsZ/q2OYEvb9qgbKPtXpH9A/srU0FwFWzCuZa6IaRb4Mw7NcttsxX2D6AAA="
  },
  "certificates/commercial-registration-en": {
    "src": "/media/certificates/commercial-registration-en.webp",
    "width": 1100,
    "height": 778,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAsAA4BaJbAC7AELXmjZLLCQAP73JymLoe3Pkllv/WJbHF89sn/3cBeLEyycBPQ7LWHr3BDKmBkzMn2ITl33aNtEAA=="
  },
  "certificates/commercial-registration-en-thumb": {
    "src": "/media/certificates/commercial-registration-en-thumb.webp",
    "width": 560,
    "height": 396,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAsAA4BaJbAC7AELXwroPQyoAAD+9ycpi6Htz5JZb/1iWxVTbVoX8cUXnivrVJMMlDLD+R9Devr0KWaIdiQfglXLAAAA"
  },
  "certificates/vat-registration": {
    "src": "/media/certificates/vat-registration.webp",
    "width": 1100,
    "height": 1558,
    "blurDataURL": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoLABAAA4BaJaQAAuUuNfeAAP70/gv6itac3J4bZSZwnAAA"
  },
  "certificates/vat-registration-thumb": {
    "src": "/media/certificates/vat-registration-thumb.webp",
    "width": 560,
    "height": 793,
    "blurDataURL": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAAAwAQCdASoLABAAA4BaJaQAA3AA/vKeyohn/jgVMb0dl8HFHAuUAAAA"
  },
  "clients/aitco": {
    "src": "/media/clients/aitco.webp",
    "width": 464,
    "height": 218,
    "blurDataURL": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSFMAAAART6CgbSQUvwFmiIiAH5TOugCbyLadXAmf2PPe/z2ZmvlRABJin5WgGBER/U9jWkUM0PZmogSW3a3fAPhryZ8ATG6cjzaKiJjqhJqC6aeN0Y1pDQBWUDggagAAADACAJ0BKhAACAADgFolsAJ0MEvIh8u77rsgAP7vqtCgGwoMKE8hk9LjOGY0YfJWtxrORllzNq1kqRxU8tcvcG00Sie9/hhwPo83i8AHHyrJXedJ0Vs3632Rfff2f+ZbwnAEZa9U2KwAAAA="
  },
  "clients/aitco-mono": {
    "src": "/media/clients/aitco-mono.webp",
    "width": 464,
    "height": 218,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSFUAAAART6CgbSM3dgT2vvuPiIB/KJV1BTaRbTu5Esg9773fk6kZfhKAhNhnJShGRET/U+tGEQO0vWlQAMtu168H3LVkjwcmO8xHE4ZETFVMdc7001qPtW40AFZQOCAYAAAAMAEAnQEqEAAIAAOAWiWkAANwAP714MAA"
  },
  "clients/al-bereik": {
    "src": "/media/clients/al-bereik.webp",
    "width": 360,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4WAoAAAAQAAAADwAACgAAQUxQSGAAAAART6CgbRs2VBT7fxERELL2/CSwiWzbyfk4+EFAVPBxEGsqhpYKB8lAEhD9IiKi/0nkfzdaAFzfuYxRsH3faIDt7KYM7NNtK9D227ECQ6VlISAo55z0npDy3PmE8055LwBWUDggMgAAAJABAJ0BKhAACwADgFolsZW5OzKiAAD+832D28MzNxteahwGp/o7I93T1miK0DQyAAAA"
  },
  "clients/al-bereik-mono": {
    "src": "/media/clients/al-bereik-mono.webp",
    "width": 360,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4WAoAAAAQAAAADwAACgAAQUxQSF4AAAART6CgbRsWl8bbjYiA7e+wAja1tTd5wUESBKQpIA5oM1NZmcACBnIw0H6/iIjof5L4P6NVALfItSfFI3LUwCNzqcB9SzmBaS3XCWy91a2CaHzwPgRik7PPDT4EE4ICVlA4IBgAAAAwAQCdASoQAAsAA4BaJaQAA3AA/vXgwAA="
  },
  "clients/alfanar": {
    "src": "/media/clients/alfanar.webp",
    "width": 510,
    "height": 191,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4WAoAAAAQAAAADwAABQAAQUxQSE0AAAART6CmbSM42blr778DcBERyPVNPQ+MYttq8xgUNAUPBHQDkERBl5JtVhhgYj2i//E9iBCqjF8ubHt9p01bTpyDx3kcW1hUoU8GQHCkBgBWUDggKAAAAJABAJ0BKhAABgADgFoloAJ0ugADmAD+7Qcv7gpPQ2eX/ca25+sQAAA="
  },
  "clients/alfanar-mono": {
    "src": "/media/clients/alfanar-mono.webp",
    "width": 510,
    "height": 191,
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4WAoAAAAQAAAADwAABQAAQUxQSEwAAAART6CmbSQ2dwBu/N72j4iAnXfKc8Eotq02j0FBU/BAQDcASRR0KdlmhQEm1iP6H9+DCKHK+OXCttd32rTlxDl4nMexhUUV+mQABEcSVlA4IBgAAAAwAQCdASoQAAYAA4BaJaQAA3AA/vXgwAA="
  },
  "clients/alkharayef": {
    "src": "/media/clients/alkharayef.webp",
    "width": 281,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4WAoAAAAQAAAADwAADQAAQUxQSG8AAAART6C4bSQ1tX/mPYiIgDy2i78RbmrbdqJDEBAF8Ikt6z8EYIGSEgv5TR2fgXE8IiL6H5CcAQCbuh5Ivro9AhhMXxbBZPqx+O9tMZSmTwuBn64LwGxpAYAHSCqXpWkalCJ5VUtU+cpVVVWJ+LGSWgAAVlA4IB4AAABQAQCdASoQAA4AA4BaJYwABAAAAP7zpJ7wdREYAAA="
  },
  "clients/alkharayef-mono": {
    "src": "/media/clients/alkharayef-mono.webp",
    "width": 281,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4WAoAAAAQAAAADwAADQAAQUxQSG4AAAART6C2bRs26hc82alrkIgI1Ep9z4LT2LZdZf/kE/gM9qUKkqeFL2kg2e+uJ92GqSGi/wH9raoAFrFnoP/K8qzAqLy1hYvKR7t/G5WX1sBH5ivArMMagFgBvdtN2+1QmRwOPqTGJ+/83vucUnE5ZFZQOCAYAAAAMAEAnQEqEAAOAAOAWiWkAANwAP714MAA"
  },
  "clients/ami": {
    "src": "/media/clients/ami.webp",
    "width": 520,
    "height": 234,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSEsAAAART6CobSM2WADtjfcEcBER8MvPYi7YRLbtVNb5DoKDHNr3DPwKJQwOEJAhov8B9vUVYP7LADierwOs+9bAuBCjdzYliVFiVJUkmgQAVlA4IEIAAACQAQCdASoQAAcAA4BaJZACdACeUEAA/vKl5rEyT0pQ7Hj6turfUD3Bnl1H3lD9+8BgoszVS4sbol68+2YFwMVwAAA="
  },
  "clients/ami-mono": {
    "src": "/media/clients/ami-mono.webp",
    "width": 520,
    "height": 234,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSEkAAAARR6CokRQ2iAXuRW8GiIggPnxBEozaSHIsqpZBYJB33z0E7nUQDsESuBzR/wD/xQ6w/fsEON9vAKx1dHAh5RyDL0U5K2czFVkRAFZQOCAYAAAAMAEAnQEqEAAHAAOAWiWkAANwAP714MAA"
  },
  "clients/arcoma": {
    "src": "/media/clients/arcoma.webp",
    "width": 479,
    "height": 159,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4WAoAAAAQAAAADwAABAAAQUxQSEQAAAART6CgbRsWl8HdiYhAnhnZBwaRbLWhSQAB4AEBHQVI4BmAFAUUBYn0iP7Hr7Q17oSSG1CTPO8N3EeUD2POJMpCv98kAFZQOCAmAAAAcAEAnQEqEAAFAAOAWiWgAnQBQAAA/vPfZ/4IL+IL+IKMkHxXwAA="
  },
  "clients/arcoma-mono": {
    "src": "/media/clients/arcoma-mono.webp",
    "width": 479,
    "height": 159,
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4WAoAAAAQAAAADwAABAAAQUxQSEQAAAART6CgbRsWl8PdiYhAnx7LDwaRbLWhSQAB4AEBHQEMEngGUhVQFCTSI/ofv9LWuF1L7kBLcr83cG9RPpxjJFEmjvtNAlZQOCAYAAAAMAEAnQEqEAAFAAOAWiWkAANwAP714MAA"
  },
  "clients/atlas": {
    "src": "/media/clients/atlas.webp",
    "width": 242,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRiwBAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSIUAAAART6CmbSM4VRL/dNNFREDXTfzBVW1rS3R/IIAGcHjVAPZNABxe7QswWuGfABY9ov8BGI5rAMiCuvEBDAqQhkhUvSlErVTYmCMoeiellCGuciZ6/ON/z9PBl/dnfE13PteEX+fzySrKiehU0ZrnOE6O6mgts90qyIVrOgWQBqZHCgCXyAIAAFZQOCCAAAAAcAIAnQEqEAAQAAOAWiWwAnQwTMGZH/xsyyCelgD+71SaCWeeeR+B3eSL55yYN728hGKsFtaiVreHPlWrGat0CZIWflRPpmaQNXPIjy9wxOUgmV1yOMpwXkdB//y4kUh71/P/bx0v0/fMX9k1/+kI3LYJ7esXh7+ZOZZD216+AAA="
  },
  "clients/atlas-mono": {
    "src": "/media/clients/atlas-mono.webp",
    "width": 242,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSIgAAAART6CgbSM3dxz2vnsCHxEB8eyi+CPc1ratRBcpwHOHlLEcLcAldPKR/1r4NDCL0iP6H4Bq2SqAu5fWLoBGBG4+IllpXkIqJfgQBRCVmnPOfbzPo2jYFV7r0a17cf432n/HPkaMdkaHhLhrWyah1Fi39ZZkySWROUl4CDfdyoGbpzu5CMAuCh0AVlA4IBgAAAAwAQCdASoQABAAA4BaJaQAA3AA/vXgwAA="
  },
  "clients/btt": {
    "src": "/media/clients/btt.webp",
    "width": 520,
    "height": 213,
    "blurDataURL": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSE0AAAART6C4bSMU35sZIiKAe6oG38Aotu0m6cnyFwVxUIF1cxBwgAU8YADDwURE/ycgvUb8VyLZ+2miYvccm4p6D/eRh0+DEAKuBXCEKgUiIABWUDggZgAAAPABAJ0BKhAABwADgFolsAJ0APRKEuveAAD+vo4Nnv50G0NfG73DdGUUEcq6FcOcfoWorteht+M9AGFufmeWJNxcLZLtfZnCIeZ4Bwcv/hdBI73eH+qw9LHsO5Db4/oLP8B1hxJgAA=="
  },
  "clients/btt-mono": {
    "src": "/media/clients/btt-mono.webp",
    "width": 520,
    "height": 213,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSE4AAAART6CobSM2VQJ93Z4REZCzyOIbGNW2duP+T4b3fhKQgJHx/2jw00AFHRTQPaL/sX8RAFDM3BhXXG3Jby9+C21++uEV/kAAvE9KEpuDRAFWUDggGAAAADABAJ0BKhAABwADgFolpAADcAD+9eDAAA=="
  },
  "clients/isf": {
    "src": "/media/clients/isf.webp",
    "width": 419,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSEsAAAART6C2bRs26NlOT8ZERGClTzsuGMW23eQGBWkCMi8ISFmhAzNsuwMcfxER/Z8AzHMz4vdb/wGlzrJnaHNtEfB98Q5JURFUNYccwQQAVlA4IEIAAADQAQCdASoQAAkAA4BaJbACdAEN3u4MwAD+9CUIzp+/6mh8R++TLXkXuBx+VoXrxpy1MsYZT9aDZMf61/8QA8GoAAA="
  },
  "clients/isf-mono": {
    "src": "/media/clients/isf-mono.webp",
    "width": 419,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSE8AAAART6CobRs4VwDLa/cWEaE2fnACjCJJUlS7ClAACjgGHWfmvuxgHY+IiP5PAOK1C/lvQmknxDr2R4BunHoPmF4bTc6Dyw6GMY/DqHApuWwBAFZQOCAYAAAAMAEAnQEqEAAJAAOAWiWkAANwAP714MAA"
  },
  "clients/lamsat-injaz": {
    "src": "/media/clients/lamsat-injaz.webp",
    "width": 205,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRuAAAABXRUJQVlA4WAoAAAAQAAAADQAADwAAQUxQSGkAAAART6CobSM2VQbj9usiIlBXPr4XbCPbVnJfxA8Vifm/ABxyJ3Yagf7nUURE/ycAMgCXiVJsLXtHkAKyJiiBrCOkCZCzwdcEJ1B1P74luKU8WYKypWx6Dt8R9PtZD8W1KsqycH26H301bD0AVlA4IFAAAAAQAgCdASoOABAAA4BaJbACdH8AGA3E7CYAAP7ukY4dZ3Ye5YU3KBeTa4T8RPtnok0hhSC9YQZOZ8H9XhhTYHszdyiPGtcHtGA6k7D2dRgAAA=="
  },
  "clients/lamsat-injaz-mono": {
    "src": "/media/clients/lamsat-injaz-mono.webp",
    "width": 205,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4WAoAAAAQAAAADQAADwAAQUxQSG0AAAART6CgbRs2VAb7fxERiG0aey0wsW1byX2JHx9OdIku3cnORGD+6zOIiP5PAFiBzKmqSms5BAQW4JqgOnA7gu+onEtDVBMCgar7CVtCsJSn5KhlS9n5HGFH0N7PCKF6qqppWlH2RdkH+znU+7YDAFZQOCAYAAAAMAEAnQEqDgAQAAOAWiWkAANwAP714MAA"
  },
  "clients/ledco": {
    "src": "/media/clients/ledco.webp",
    "width": 520,
    "height": 199,
    "blurDataURL": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4WAoAAAAQAAAADwAABQAAQUxQSEsAAAART6CmbSQ2eAxOP/U2f0QE+Dmi5w1GtW0ruf8n0ABwXwKkAYu5SxEdOwmoHtH/QDS/kwKSfy8DgOMbGQtpzr1g5wlz5yIkUGlrrQIAVlA4IEYAAADQAQCdASoQAAYAA4BaJbACdADRz6BGwAD9mk874cWpoU6ItTEoF/nfeKatJDMMg+XwFOPf9JOPpjr/vPQLXBK09zUyknQA"
  },
  "clients/ledco-mono": {
    "src": "/media/clients/ledco-mono.webp",
    "width": 520,
    "height": 199,
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4WAoAAAAQAAAADwAABQAAQUxQSEwAAAART6C2bRs26hPs1M17kIgI8Ds9twaj2LabvDjo+8xLDASwwL6jIQZo+24ArEf0P+DnJwsg/fvkABxvLhlJeexDMRpCfnWoSKDRSikFVlA4IBgAAAAwAQCdASoQAAYAA4BaJaQAA3AA/vXgwAA="
  },
  "clients/manar-alomran": {
    "src": "/media/clients/manar-alomran.webp",
    "width": 520,
    "height": 122,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4WAoAAAAQAAAADwAAAwAAQUxQSDMAAAARN6CmbSQ2ON7YvtB5GB8Rgb3mLxRCtgIVwomQwGFQKt9fIoiI/ieCHnKu+hYhDyHCIgIAVlA4IC4AAACwAQCdASoQAAQAA4BaJaACdAD0gbJgAP7ApyG7zqPYTD95iDOp9lPt/wE0AAAA"
  },
  "clients/manar-alomran-mono": {
    "src": "/media/clients/manar-alomran-mono.webp",
    "width": 520,
    "height": 122,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4WAoAAAAQAAAADwAAAwAAQUxQSDIAAAARN6CkjSQ4SBcuep2ck4uIwI55QSEkK1QhfBEiCKGn8vwhCiKi/xPAkpcNzAIse4+aGVZQOCAYAAAAMAEAnQEqEAAEAAOAWiWkAANwAP714MAA"
  },
  "clients/metal-details": {
    "src": "/media/clients/metal-details.webp",
    "width": 520,
    "height": 209,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4WAoAAAAQAAAADwAABQAAQUxQSEAAAAARP6C4bRM41RN4ExEB3870wSi2rTaPYoE9EjrrLqAlBooG/A8REdH/AGL4KAD0e/OTrlscta+fvB8GtOLeu9QKVlA4IDYAAABwAQCdASoQAAYAA4BaJbACdAFAAAD+5RYxvlSyTvftiED+5kvXoxUIv2BePhkZanlpOfRAAAA="
  },
  "clients/metal-details-mono": {
    "src": "/media/clients/metal-details-mono.webp",
    "width": 520,
    "height": 209,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4WAoAAAAQAAAADwAABQAAQUxQSEEAAAARP6AmAAg2Zm+XCiIiQG9r88Eotq02j2KBPRI66y4g7RtIsYD/ISIi+h9ATh8HgI2mXOUitcx8f5puAYwWHmq9AwBWUDggGAAAADABAJ0BKhAABgADgFolpAADcAD+9eDAAA=="
  },
  "clients/obeikan": {
    "src": "/media/clients/obeikan.webp",
    "width": 404,
    "height": 219,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSF8AAAART6CgbSQUvwRmiIiAR4221ALTAACT4OTJAThUp3t1yC7dKkkO4PiI/gcBIlcSwZlZH4MsdSkFQ3OfJe2mtJ2XWesvt3OgRPH3tFzzXvt/ub1rFQYSNkGAgAxFUQQSBABWUDggJgAAAJABAJ0BKhAACQADgFoloAJ0ugADmAD+8JtD7U2Kqed3rynxK0AA"
  },
  "clients/obeikan-mono": {
    "src": "/media/clients/obeikan-mono.webp",
    "width": 404,
    "height": 219,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSGAAAAART6CgbRs2VBD7fxEReLIILwswsW1bCU7+wABcqtO9OmR/0K2SZAAMPqL/gaHYk2X5zO2P4m0NKtHUvQeyfs46gEUfLq93OZlg7xmuZW+Df9zetY5CWbC4kEeKLEkyJ3NWUDggGAAAADABAJ0BKhAACQADgFolpAADcAD+9eDAAA=="
  },
  "clients/rakayiz": {
    "src": "/media/clients/rakayiz.webp",
    "width": 292,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4WAoAAAAQAAAADwAADAAAQUxQSFgAAAART6CokSQ1tgKYnscQEQG/tC1rH8E2ABgZOQzw0+aZwKXSvUvojKBUqwzw7ivMENH/CQCAOAJzrqylsbaPw8JnMtp9jf7hOAYvO03ShIVq5ozZk6pqrz7xVlA4IEoAAAAQAgCdASoQAA0AA4BaJbACdDiAAQv1K2zAAP7ZWfk7qPDVfbtG6/qGT1wZmg51VdD3Xb4C0n6NtjqPXfxKr+u4Q317eOcWSmAAAA=="
  },
  "clients/rakayiz-mono": {
    "src": "/media/clients/rakayiz-mono.webp",
    "width": 292,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4WAoAAAAQAAAADwAADAAAQUxQSFsAAAART6AmkiQ1dwoYoo8YIyLgRxbcVRqY1tbe5E8A38GmTJDQXR8Bj8WxBrbDvPwwQ0T/JwAAbAvQMcLmEls/DozdE1I9i/WPDb3xwl1HOEIqpWMZy1jESRw3seYxAFZQOCAYAAAAMAEAnQEqEAANAAOAWiWkAANwAP714MAA"
  },
  "clients/raqyah": {
    "src": "/media/clients/raqyah.webp",
    "width": 499,
    "height": 236,
    "blurDataURL": "data:image/webp;base64,UklGRswAAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSFIAAAART6CmbQMW9tuNiIBHp+bBKLbtJikOEgPNwC8rtkkw0GHZQQAGwDomIvqf4vdWOuEMZLZbWm74KpO69sB3Rmoi4zLTc/UjrLXBFKMjUsSJhdMCVlA4IFQAAADwAQCdASoQAAgAA4BaJbACdAEfsBj4liAA/vbjZh7ChyrIhBstb5FQtAWYh617iM8ld0Y/LtA8kS+N50bsEZb7DdiNcz/u/m/BE3HeFtUfYPhlQAA="
  },
  "clients/raqyah-mono": {
    "src": "/media/clients/raqyah-mono.webp",
    "width": 499,
    "height": 236,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSFUAAAART6C2bRsWe6wpERHIm/vnAaPYtpuqe7GQ/wUkYCDFAB3WHZYdtk0BEf0PAIBloaCkaTNek/mK/orqrdnje0pcE/p4ntx39oNZenKN9ypNKUnTTCgGAFZQOCAYAAAAMAEAnQEqEAAIAAOAWiWkAANwAP714MAA"
  },
  "clients/sahar-alriyadh": {
    "src": "/media/clients/sahar-alriyadh.webp",
    "width": 189,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRlABAABXRUJQVlA4WAoAAAAQAAAADAAADwAAQUxQSHgAAAART6CgkaQ2+BZ6f8AAERHwzNPX8cOJbVvLqu/8/keBAThUl6gDcKhuVe9fcYjof0CpAcDr6wCD+HMALvoqyf0o7f/GqyvNT840JTXb7ikhFU9mMLlploTlVVsT5su460N21i9YsGhVBATVShYymUQ6ExqTWraWq1pWUDggsgAAAFADAJ0BKg0AEAADgFolsAJ0MEg/YD0gCZTMvPzyBEG/yWAAAPjWYyz0GAjVqTeiz4nAO85VcKiufZGuuV4pcubKOD3alGgeuFVZGP2h1sDu7CCLkRgFPol3zz+kLxfKddh+MjNQbGQ3rixx+WrzB/7zk3mJR/9MaOPrv7oD1f3/4//GYPYUH19hy/60Fx9Fqn/Gb7X0P+M0To3ZGKD0wfeNlrbnR362u7tCDFjK+DXowAA="
  },
  "clients/sahar-alriyadh-mono": {
    "src": "/media/clients/sahar-alriyadh-mono.webp",
    "width": 189,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4WAoAAAAQAAAADAAADwAAQUxQSHoAAAART6CmjSQ3eAiuy/m+/YgIeGTuo/jhtrZt09a2Hj5CFuD/UyNkAUZohd63gMeI/gc0+wB4YQKYR+ED+IahCryeoe6x5U2M9u/Epmg0HCXfeanxdjLrv7YFOPq62rA7mkkaKtt13YHDsC0gM+1UoFyutNs5az3rzHpdB1ZQOCAYAAAAMAEAnQEqDQAQAAOAWiWkAANwAP714MAA"
  },
  "clients/ssf": {
    "src": "/media/clients/ssf.webp",
    "width": 520,
    "height": 145,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4WAoAAAAQAAAADwAABAAAQUxQSEkAAAART6CgbSM3dhj2vvuPiIAs5onAD0axbadJJEQCGvgTAyiBttA64DV324n4iP7HJ/VX93ZlXNSvDsh0Gut4hgy2+36RDMN37AcCAFZQOCA0AAAA0AEAnQEqEAAFAAOAWiWwAnQBA/YIOAAA/ttd4/t5yWt4vNFfWb4A7kcck0r72WXp1wAAAA=="
  },
  "clients/ssf-mono": {
    "src": "/media/clients/ssf-mono.webp",
    "width": 520,
    "height": 145,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4WAoAAAAQAAAADwAABAAAQUxQSEcAAAART6CmbQM2Vwb9ol4jIkIsNPPBKLbtNJk4iAUyAAZQAm2pCrhr7rYT8RH9j4+pr+z1SjDLXx484Wkow+kTN931CyXRvnEfAQBWUDggGAAAADABAJ0BKhAABQADgFolpAADcAD+9eDAAA=="
  },
  "clients/steco": {
    "src": "/media/clients/steco.webp",
    "width": 520,
    "height": 207,
    "blurDataURL": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4WAoAAAAQAAAADwAABQAAQUxQSEQAAAARR6C0bQM2FN7FGhFBZHU72ES27VTaIfVvsAACMnW6TwBZAR8J9ET0P+DPANr9u2NgDed5FhHm0vkEt75VPr6DSRGVl1ZQOCBaAAAA0AEAnQEqEAAGAAOAWiWwAnQA3EaKs4AA/vNZrL+MYpLq25L9Lm2tBuKgNEOoAjVhYCIXCBLUYSWuIO8A7tkMbnB3cgH27pMxURV83TwoTfBMGGnsgohIAAAA"
  },
  "clients/steco-mono": {
    "src": "/media/clients/steco-mono.webp",
    "width": 520,
    "height": 207,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4WAoAAAAQAAAADwAABQAAQUxQSEYAAAART6CgbRsWF8HdiYiAW5nqg01k207OT/0DDV8AWcF79NlBcvAtUKM+ov8BfwLot+/1wFLO68wVMqte92My9lY3ZRJVR2MZVlA4IBgAAAAwAQCdASoQAAYAA4BaJaQAA3AA/vXgwAA="
  },
  "clients/tbk-metal": {
    "src": "/media/clients/tbk-metal.webp",
    "width": 520,
    "height": 116,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4WAoAAAAQAAAADwAAAwAAQUxQSD0AAAART6CobRs4VAj3nouIQN/OMQOj2LbTxAoLwDUne7IA+1goKehUcEVE9D+fdzIEWfHHo+fKH98xhN4G+BkPAFZQOCAwAAAAcAEAnQEqEAAEAAOAWiWoAnQBQAAA/vEQf/8/jhZOB5ZfUbqn/89nSRH//OZeAAAA"
  },
  "clients/tbk-metal-mono": {
    "src": "/media/clients/tbk-metal-mono.webp",
    "width": 520,
    "height": 116,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4WAoAAAAQAAAADwAAAwAAQUxQSEAAAAART6CgbRs2VQD7n8AiIuDv1UM3YBTbdppYYQG45+zJQib7FAyggk4FV0RE//N5B0OQZXc8eh/p4zN432oHP+MBVlA4IBgAAAAwAQCdASoQAAQAA4BaJaQAA3AA/vXgwAA="
  },
  "clients/trolley-carriage": {
    "src": "/media/clients/trolley-carriage.webp",
    "width": 502,
    "height": 231,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSEQAAAART6AmAAg2JsDeXCIioLzpGc+gqrZt6KLAi2BqMP1PGRTwJYAMVJD3LR0i+j8BAIoHp3EF0+soRm9LhpkB2G9ovfcYA1ZQOCBCAAAAsAEAnQEqEAAHAAOAWiWwAnQAtqv40ADHXaOlEiG9PI+1/zu5//vPiXe/YlUv05q4yLuwcd/85X90m9n++OJygAAA"
  },
  "clients/trolley-carriage-mono": {
    "src": "/media/clients/trolley-carriage-mono.webp",
    "width": 502,
    "height": 231,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSEoAAAART6CobSQ3twx63733RURArjd+ewxXsW07zQIMIKH/dwxwMYCFJoEkChILcR7R/8Degvz+JdB9vhkU/ycFx4KqqoZ6qKpYt4iIFVZQOCAYAAAAMAEAnQEqEAAHAAOAWiWkAANwAP714MAA"
  },
  "machines/fiber-laser-3kw": {
    "src": "/media/machines/fiber-laser-3kw.webp",
    "width": 386,
    "height": 213,
    "blurDataURL": "data:image/webp;base64,UklGRuAAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSFYAAAART6CokSQ1th6Yj14XEQH6vWoeBtjW1p7kS7DWoaWidyltBYagdUZIFrB9ww4R/Z8AILdhnDwAMcojC0L0EIqzEcWmtFZ742izK3/KR7Pv5Q6wBsQPAVZQOCBkAAAA0AEAnQEqEAAJAAOAWiWkAA+H7i0NrbAA3eolZRE/ezubxr44bzksQWkMV+NWoM97cnEbZ3sJ9raBZ52/+XyERmbaaNlHD94biwUmOTvZ//01ar0Y9ZF+5d/N9NZiAVz4oAAAAA=="
  },
  "machines/fiber-laser-6kw": {
    "src": "/media/machines/fiber-laser-6kw.webp",
    "width": 557,
    "height": 209,
    "blurDataURL": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4WAoAAAAQAAAADwAABQAAQUxQSEUAAAART6CgjSQ1dxb47pk/IgLw95GOzgxWsW0r2TMUsAgUcAI4faCC/utuHtH/AMgCSCFb5ziqi27T67xVvZrl0GtMIGynGAAAVlA4IFoAAADwAQCdASoQAAYAA4BaJZQAD4lwdFNJDsQA/qWWOlP/mDKqfEKPSh7r8D8+uTWCzdhH2k5bSO/0+asZxK3imn4/0/ejoIDXmeytPQ5iUz5zjJjnNwB4F3gAAAA="
  },
  "machines/fiber-laser-combo-12kw": {
    "src": "/media/machines/fiber-laser-combo-12kw.webp",
    "width": 439,
    "height": 207,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSEMAAAART6CobSM2VQp9jpsREZidC18DVbVtQ9f4bamgggRjhScAHTQYIujrdYjo/wQATgJAmnu1IPC+V7+/ZQzTGUrjXIoeAFZQOCBGAAAAsAEAnQEqEAAIAAOAWiWkAALrFPyF0AD+6FBLJ920GKUJfTydfERsRe2HOe32Dfz9PSB7batp9g9VddU0NFgsL6UsWAAAAA=="
  },
  "machines/laser-welding": {
    "src": "/media/machines/laser-welding.webp",
    "width": 181,
    "height": 177,
    "blurDataURL": "data:image/webp;base64,UklGRu4AAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSFgAAAART6CgjSQ1dSaY7yEiAjL4V4wjGNW2reQiAT4RnKkTwOdWgSaagP/yfo0Q0f8JgNhAHsgiV1iPs4sBxomIfDCSFO0vuCyVoVQwBex8DnDxbxkA9GEOuQcAVlA4IHAAAADwAQCdASoQABAAA4BaJYwAD46qJTEdVAAA/q7Z5efs/52mMbVYYe+XFDalj02gs544xSv9AC1Hzmitlf+SRTpFOukjvhWqkBxX5d92E/rQmnTAmScky9XSKCNw/OvdclhYQSLSuyeVFT4HOgkAvRAA"
  },
  "machines/press-brake": {
    "src": "/media/machines/press-brake.webp",
    "width": 326,
    "height": 211,
    "blurDataURL": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4WAoAAAAQAAAADwAACQAAQUxQSE8AAAART6A0khQ2+hqbk8LRABERWLp6GXYwiGw3SnoqaAWUywASGKQQDUgICpKvt8FDRP8ngFREpBAZANTgHe3S6X4V7mdeh1/tZ9h0BHqYmfMJAFZQOCBuAAAAsAIAnQEqEAAKAAOAWiWIAnR/CP/h45oLk99hiIkAAP7KaDA9MAc/Fc4DgA1geuQnzW2+enlT5w7IM67eUzjCIlX1pQVjdVL6O6iq2JTzKkIfJMVTHhyIXApGlm43nh5TAQp1ulXbjCoU7f/aQAA="
  },
  "machines/tube-cutting-12kw": {
    "src": "/media/machines/tube-cutting-12kw.webp",
    "width": 359,
    "height": 206,
    "blurDataURL": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSFAAAAART6CgbRs2VBjdvxERkNZ6qhvYRLbt5BDrX9FTYQABGQOYoMypjwrCFYyHiP4ngLEASM7GBWgln72MByng2ZZXut36lSRFmGz6JAGE+VzxA1ZQOCBaAAAAMAIAnQEqEAAJAAOAWiWkAA+LT7syzRy/6gAA/raWXRL0i3bxcqqYJFfw9STs0dV9Z4FDmpKZAGGvsdq78+78U/Fe61CdjfZH8JM14npWHYliPW8P87AAAAAA"
  },
  "projects/billboard-structure-1": {
    "src": "/media/projects/billboard-structure-1.webp",
    "width": 357,
    "height": 208,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoQAAkAA4BaJZACdH8AGCZkEOQAAP7YFtyEea7VfiWRULtKRbbXFOyXbS/S+hBzVl3wR7okd4AAAA=="
  },
  "projects/calligraphy-sculptures-1": {
    "src": "/media/projects/calligraphy-sculptures-1.webp",
    "width": 322,
    "height": 241,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAwAA4BaJYwAAfQMXmTXwAD+Z8vO1U02C/fBJpNTFWR2JSiHFuG2LNiSFFj/xq+4VtgjBxAuUAVpq2Mv/1aqv3V6alqASAA="
  },
  "projects/canopy-tree-1": {
    "src": "/media/projects/canopy-tree-1.webp",
    "width": 321,
    "height": 465,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoLABAAA4BaJZQC7AELY0+1jlrQAP7oojs21WgJg36hcOZ60zsnhOw2Xd+6hH27yoTyOJCkYvBX9X/ftnIneShwoPdioHKj86QqI2zmSoFppDrLAAA="
  },
  "projects/car-park-shades-1": {
    "src": "/media/projects/car-park-shades-1.webp",
    "width": 320,
    "height": 240,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAwAA4BaJYwCdAEPS6aLAAAA/e+pdL4RCM0oi475XiXBPqUrun5YjSvyCRW/gYp+MjLU7V7LkVnkyAA="
  },
  "projects/car-park-shades-2": {
    "src": "/media/projects/car-park-shades-2.webp",
    "width": 156,
    "height": 208,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMABAAA4BaJbACdABwf06RdAAA+ZjvafSyRiJjfFpeGvruR1bpovZyLFd16acq/h3cwzlaRCfdnZ+wwBZAAA=="
  },
  "projects/chandelier-1": {
    "src": "/media/projects/chandelier-1.webp",
    "width": 322,
    "height": 322,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQABAAA4BaJZwAApr/MHW72AD+cV2li+EzPK3UqmRZB/aw4kOjKFR3Oo1gWfSRpM23+6NYL8hGarkoDx96CNoFYEAAAA=="
  },
  "projects/clock-tower-1": {
    "src": "/media/projects/clock-tower-1.webp",
    "width": 305,
    "height": 410,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAQCdASoMABAAA4BaJbACdACm3qwA/qUQDXODS8PtLfcQorddmWKMMxd8jtYQzTfB5WmMVXD3H+Axi3qOq92vWIYS76eg+GHK0WF0mhAAAA=="
  },
  "projects/clock-tower-2": {
    "src": "/media/projects/clock-tower-2.webp",
    "width": 114,
    "height": 234,
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoIABAAA4BaJQBOgCHczfKiFHAA/vaNpYSGeiLw6ujU11d7Y6aE+xxmIhSlT2v4cPAAAA=="
  },
  "projects/clock-tower-3": {
    "src": "/media/projects/clock-tower-3.webp",
    "width": 157,
    "height": 209,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoMABAAA4BaJagCdADcJP/tBYAA/ozb6zv6E2kAaqRB3zVzbZWm7oAEsu9Cu5PHFxSSNfo+ieoYCqjhJrb9WBSF/YicnwJaZxWzbM5Z2doAyGLYkbGemAAA"
  },
  "projects/curved-frames-1": {
    "src": "/media/projects/curved-frames-1.webp",
    "width": 322,
    "height": 252,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAA0AA4BaJYwC7ADpJ1xfigAA/us1kiL75KZ+rzQQXgAN2AhUSWLEKiUCFBg1ugXqsICoZlApIn8NuRjyS7aknp8nKZuCaiSqrWYWIAA="
  },
  "projects/dome-finial-1": {
    "src": "/media/projects/dome-finial-1.webp",
    "width": 156,
    "height": 208,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoMABAAA4BaJQBOgBuyITv9V0OwAP2evCP1Za1lHHhOQ5Da+n5A5NVr+W0ToLnW93AhYPY8gePqEdXFSZfJ0yN1WtEV9dCogsDlTrAA"
  },
  "projects/dome-finial-2": {
    "src": "/media/projects/dome-finial-2.webp",
    "width": 423,
    "height": 226,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQAAkAA4BaJbACdLoAAQs+eAD6XCfIpHiDs+S+uyfevX18AY5s24AA"
  },
  "projects/emblem-sculptures-1": {
    "src": "/media/projects/emblem-sculptures-1.webp",
    "width": 154,
    "height": 274,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoJABAAA4BaJQBYdiFsih44fHZAAP7AusKAN/3GOXqPQuhfR/m0yiz1PHOi0b4s7BbBjsVAcmtvUkXzKQfOMVFAGM896gDnAAA="
  },
  "projects/emblem-sculptures-2": {
    "src": "/media/projects/emblem-sculptures-2.webp",
    "width": 167,
    "height": 223,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoMABAAA4BaJZQAAlq4NmMDAAD+qxhnht0dgkkThMFVTrf5ycAXQUyUitJCgPU+Wd7kDC+ojaaH2z6mL88OZ8whnPnni1j44AA="
  },
  "projects/gateway-signs-1": {
    "src": "/media/projects/gateway-signs-1.webp",
    "width": 159,
    "height": 220,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoMABAAA4BaJZwC7AEOwXPV6K/AAP7282ksHNsvv2TGn1fTT7yjqikxqc3pIQsB6AJSnIJk2X3T5x/lSk8x43oAAAA="
  },
  "projects/gateway-signs-2": {
    "src": "/media/projects/gateway-signs-2.webp",
    "width": 173,
    "height": 234,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMABAAA4BaJZQC7AEN6UgixAAA/va0HwMR9Fkmcx6rItMaGG7+uNWK43APVOFf31egpSXJViXFtzsOs1tPHKRhESFdcQQAAAA="
  },
  "projects/gateway-signs-3": {
    "src": "/media/projects/gateway-signs-3.webp",
    "width": 92,
    "height": 163,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoJABAAA4BaJagCdEf/gfLsZV4AAP52J+Q2Z9tR61vMZcn10+LQWl1TwuLgyuDQobd/xnfDDgC+USLvlNpdp87QcAA="
  },
  "projects/geometric-lanterns-1": {
    "src": "/media/projects/geometric-lanterns-1.webp",
    "width": 322,
    "height": 241,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAwAA4BaJYwCdAEQEVrgKuAAAP7zOWutmsIu8L1Chqzh+ZsJyPRu15wUA35gmECG3vO5BCrd930jd693x1TR+mkJhWQnIJQXL0tcAAA="
  },
  "projects/heritage-cannons-1": {
    "src": "/media/projects/heritage-cannons-1.webp",
    "width": 167,
    "height": 223,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMABAAA4BaJbACdADwh2IhQfwA/fnnJXgoUecaiyCTGHD4x+GwJAD6SJqsxSP1mo+cBxmvXjbvcfPu3IUjT4AA"
  },
  "projects/heritage-cannons-2": {
    "src": "/media/projects/heritage-cannons-2.webp",
    "width": 185,
    "height": 138,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAwAA4BaJZACdADFIfw63AAA/u9Z3I8424+5kVSOOUJjlIe19346UzdjQtRx+VFlQ3SQ5XP5NJ2aBcV30tUtw4cAAAAA"
  },
  "projects/heritage-cannons-3": {
    "src": "/media/projects/heritage-cannons-3.webp",
    "width": 160,
    "height": 120,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAwAA4BaJYwC7AEOefkv33AAzixXpwt24bNL3ZyXlHYeqyFig5L3Pbxg+yqPIZEhfUnbgnOPZpR2Sna2wAAA"
  },
  "projects/heritage-cannons-4": {
    "src": "/media/projects/heritage-cannons-4.webp",
    "width": 160,
    "height": 120,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJYgCdAEQ/ir9SloAAP7pT8Ibnh44ae90rciHLTXTTFY3nJx0wKAgPKfqRBQXXjkfZmBQeT0/WKcH9ZQuaptcG4yNbOlOXgAAAA=="
  },
  "projects/laser-cut-bench-1": {
    "src": "/media/projects/laser-cut-bench-1.webp",
    "width": 256,
    "height": 191,
    "blurDataURL": "data:image/webp;base64,UklGRuAAAABXRUJQVlA4WAoAAAAQAAAADwAACwAAQUxQSGQAAAART6CmbSQ2eCTue5l++ogIeB5/hQWnsW2rzg42wJL9U5lIJscgv0wcJ5qhgffm9HuLiOj/CHQ+dQC8/uY5SA1g9vLSMEZ0K3lpE3cZXJB2AC5oDMD9XzT2m7QRrVLGZJs0Wk0AVlA4IFYAAADQAQCdASoQAAwAA4BaJagCdEf/gQ9SQAD2RjK7RKUOx4dBtTV0OhVUxreMtaP8Kvwl/wdOWKfTUvkf7531BCHQFabMSC594B7/U3BbRASonNTzVaxAAA=="
  },
  "projects/laser-cut-components-1": {
    "src": "/media/projects/laser-cut-components-1.webp",
    "width": 322,
    "height": 241,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJQBOgMXDwOAGptwAAP4nVE1nMZSxWzpQtciaohbhqp9xz2ZRp9xpMMnZIASsP+BvuzA8EjI3YA/79qQW7oowhKI92wUO3YvOVD43n9eTqAAA"
  },
  "projects/lattice-cubes-1": {
    "src": "/media/projects/lattice-cubes-1.webp",
    "width": 381,
    "height": 254,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAsAA4BaJagCdH8AEaOfegAAAP7u8gQmg5xHj2UrT4lycCG3oQJECfZQd0rKut6WaJ7upsHPHglW1rvVn52musAAAA=="
  },
  "projects/leaf-sculpture-1": {
    "src": "/media/projects/leaf-sculpture-1.webp",
    "width": 156,
    "height": 208,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAQCdASoMABAAA4BaJZACdADcAZgAAP73glq07QG7PneYgw/s4P9Ot284Rok2V4NlzUUZoGiMzUr0MVdNtV0E+VBnlYTEwBC8+BfUClscYpHQyzJgtUoAAAA="
  },
  "projects/leaf-sculpture-2": {
    "src": "/media/projects/leaf-sculpture-2.webp",
    "width": 219,
    "height": 389,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoJABAAA4BaJaACdH8AE1JY+gAA9wSql33UpIj5BwAmX1MjB8Foqd/qABbAOaF7DzqHKLz/Ah8GfvUibBLnNhQAAAA="
  },
  "projects/lighting-tree-1": {
    "src": "/media/projects/lighting-tree-1.webp",
    "width": 405,
    "height": 270,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAsAA4BaJQBOgA8C4M4AAP73wRuw+QPQ5ZjFVqtne5NB3nR5mO7poEohyKJQdMjMM8+WdZbqNMgfdUavZc+n2gAAAA=="
  },
  "projects/litter-bins-1": {
    "src": "/media/projects/litter-bins-1.webp",
    "width": 69,
    "height": 123,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoJABAAA4BaJagCdADcI82PfwAA/CFTbPxvy5o77ttvNikbllKcHVqyymEZfVYCBsV9M+FVp1jZj4RrRMeCajyKgAA="
  },
  "projects/litter-bins-2": {
    "src": "/media/projects/litter-bins-2.webp",
    "width": 110,
    "height": 129,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoOABAAA4BaJaACdAEN43a8oR4AAPlpqvwvK8LHqpzrM+hAQl9yw/GCjwSTF51ryqtzcFLCzYzrX6UckXEgaN1zxfl53tSdIpP0TWfgAAA="
  },
  "projects/litter-bins-3": {
    "src": "/media/projects/litter-bins-3.webp",
    "width": 54,
    "height": 124,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoHABAAA4BaJZwAAuTs4eycAAD+8DeAtx7oGqAt2tIBjuSPXTPq/W5L7eiqj2UdMA+gt1h9rMeyRhiqOgQAAA=="
  },
  "projects/palm-canopies-1": {
    "src": "/media/projects/palm-canopies-1.webp",
    "width": 253,
    "height": 328,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMABAAA4BaJQBOgBVTUvpG8wAA1jw2I7n6oC3FtPmbdR2afnEJ8LyHvNeCH8lxZC+hLAAA"
  },
  "projects/perforated-beams-1": {
    "src": "/media/projects/perforated-beams-1.webp",
    "width": 205,
    "height": 274,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAQCdASoMABAAA4BaJZQCsACPH+gAAP6jNru/vO9jO/CQ3K0LRSZ5Kt+lWEed2fphydO9J+85aJzXWAst7DnisLj4VcDxEOXapAPalWULKQ9Z1gRWTJGFCNb4AAAA"
  },
  "projects/perforated-beams-2": {
    "src": "/media/projects/perforated-beams-2.webp",
    "width": 277,
    "height": 208,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJQBOgBxN0+E0LMqAAP7KOL90OgmYGjjxt9WP+suc7dRmy3LhJ3PS/tCrb1YL0AJy6JZbdzsXjVWA0CT4HkfBsgtaY1GRdWNAAA=="
  },
  "projects/perforated-canopy-1": {
    "src": "/media/projects/perforated-canopy-1.webp",
    "width": 322,
    "height": 214,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAsAA4BaJZQAAm4ZGVUmsAD+0odFCHp5Q14xM1bGiuZneWcgM9gn/ofucotQO9ttPb2VfAgAAA=="
  },
  "projects/perforated-seating-1": {
    "src": "/media/projects/perforated-seating-1.webp",
    "width": 277,
    "height": 208,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAwAA4BaJbACdH8AEZ2IosTgIAD8MgUFhNE0TeG80DJm4r96jg7pzAK/sjoGsbwYa2PIMpG3mOkm80FVK35lJOqpcF5iemG0Pzdl2kaMBOFWAAA="
  },
  "projects/perforated-seating-2": {
    "src": "/media/projects/perforated-seating-2.webp",
    "width": 288,
    "height": 216,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAwAA4BaJZQCw7EerFV4Bs9AAP6rnTSNIS4ZkQBJeup+SDV2zOJbU7YKsDlNcrHM3DQ5cHObVERHPmTofMoakQAAAA=="
  },
  "projects/screen-enclosures-1": {
    "src": "/media/projects/screen-enclosures-1.webp",
    "width": 382,
    "height": 244,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAoAA4BaJZQC7ADzHXkfAAD9/TKqFrnfncZ7aIAkne1zA7VbEUY4W0Fhqm5AN7+SEpvELlZuRtAkShgAAA=="
  },
  "projects/screen-enclosures-2": {
    "src": "/media/projects/screen-enclosures-2.webp",
    "width": 312,
    "height": 187,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAoAA4BaJYwC7ADQO7HPXQAA/i8qw729Zl6S+fnUuNY1j/abLH2i+HeqQqc8oZzbfAz7TVjhamAA"
  },
  "projects/sculpture-fabrication-1": {
    "src": "/media/projects/sculpture-fabrication-1.webp",
    "width": 154,
    "height": 207,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoMABAAA4BaJZwAAlpDnAR43MiAAP7CbheDSEvrRfKsjOtlFJajxst2tju5EaaoFAIA4s8VIWFZqJQhi5AQ7FTpddvNPySGCSl9aQTSR5X+Db5iz38mDq/QgAA="
  },
  "projects/sculpture-fabrication-2": {
    "src": "/media/projects/sculpture-fabrication-2.webp",
    "width": 168,
    "height": 224,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMABAAA4BaJZQCdAEHIQObqKAAAP6FmliJzLiYrqVoqVPe5CVyQF5EoBiaYYqtngpXlm/sU6Rhb97TU+oOY5/HyMAINiyt0AAAAA=="
  },
  "projects/seed-sculpture-1": {
    "src": "/media/projects/seed-sculpture-1.webp",
    "width": 344,
    "height": 229,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAsAA4BaJYgCdAD8ENiF25CAAP710pvjwPOJvw+WKcPKuJhkmPMLHox+Xs1qu9nLb8GKbbvZWhkRhFSObyLtdM8eFwko2m0gAA=="
  },
  "projects/stainless-handrails-1": {
    "src": "/media/projects/stainless-handrails-1.webp",
    "width": 321,
    "height": 241,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwAA4BaJZwAAu18JNG/4YAA/fzWV7AMuWGW4unEUSNEDDYi7oJw8vMMpXELOuco32LiRCdiQP/x7/UIAA=="
  },
  "projects/stainless-landmark-1": {
    "src": "/media/projects/stainless-landmark-1.webp",
    "width": 413,
    "height": 216,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAwAgCdASoQAAgAA4BaJYgCdH8AE4dmSpkgAAD+3r6vYwBN3MPHiOIRBchqYm7WbsqJhBowvR8nO9+AAAA="
  },
  "projects/suspended-lantern-1": {
    "src": "/media/projects/suspended-lantern-1.webp",
    "width": 416,
    "height": 400,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAA8AA4BaJYgCdAEGGrSxZAAA8YSFfn5YbB/UxZFpDtr6h4S0T+qaAbrkcDNQJhzTdHJMWBK4/pS6fncsMmT4wVJRYBnDOAAAAA=="
  },
  "projects/tower-replica-1": {
    "src": "/media/projects/tower-replica-1.webp",
    "width": 301,
    "height": 401,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoMABAAA4BaJbACdADYo6QAAP1GyUwQpHxePBW2kPAlOXPIwDbcWm1MwXzZBGwtNO5ah76ld5pw2E7g3FIYJzoA"
  },
  "projects/tree-grate-1": {
    "src": "/media/projects/tree-grate-1.webp",
    "width": 470,
    "height": 212,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoQAAcAA4BaJZQCdAE1eZPpMftQAP6em5EtSMFGqWZWj8h4H1BTvUwu/3IbwxQA"
  },
  "projects/tulip-roundabout-1": {
    "src": "/media/projects/tulip-roundabout-1.webp",
    "width": 464,
    "height": 356,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwAA4BaJYwCdAEVVXpSu+nAAP73laEBzL952rb026v/0EWm9k3rQBJw6gINCGe28B8oFdSNZ53pPOrjHw1X8Qjaz2gAAAA="
  },
  "projects/tulip-roundabout-2": {
    "src": "/media/projects/tulip-roundabout-2.webp",
    "width": 117,
    "height": 208,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAQCdASoJABAAA4BaJbACdADYXAAA/kCYm36uF8YzZ+xwf//+aR6NVTytPV2+lKdfjJpW9Kr1IqS8j+bT0SzS8RVNvgAA"
  },
  "projects/vision-globe-1": {
    "src": "/media/projects/vision-globe-1.webp",
    "width": 156,
    "height": 208,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoMABAAA4BaJYwCdAYulaABmqXNgAD+13GiD+Ew9WwLz71Sde8v6jQEHPgwmO80cPLMB4+gR6mlO9UrsReVFIt5Q6Rk59WpNlKhlfbUOP3sn3BWEwLqkPJ1K3W8AAAA"
  },
  "projects/vision-globe-2": {
    "src": "/media/projects/vision-globe-2.webp",
    "width": 212,
    "height": 285,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMABAAA4BaJQBdgCHhySvfFCgA/pfdQGEPPx7sSymiClk1Rv3EdVbYciLCloC6/2oJXSXRaQKoQjbDPAwAAA=="
  },
  "projects/wave-sculpture-1": {
    "src": "/media/projects/wave-sculpture-1.webp",
    "width": 370,
    "height": 208,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJYgCsADwSrVGAAD+9uBYRQPxpGyD1MoClxs37vVdg++me6nRuN7gFg6MnTmeq+4DYkwAAAA="
  },
  "projects/wave-sculpture-2": {
    "src": "/media/projects/wave-sculpture-2.webp",
    "width": 156,
    "height": 207,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoMABAAA4BaJZQAAlLxQePEAAD+3g7qyoBxfKxL7MnEO2tBbJxd2HZ0i/ElyLcKPV2eslIO55wa3PfaIFMGQdyaBc/6c6/aA/vnrFAA"
  },
  "projects/wave-sculpture-3": {
    "src": "/media/projects/wave-sculpture-3.webp",
    "width": 117,
    "height": 207,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoJABAAA4BaJQBOgCPSXJjKgOLAAP7c5bnBCj8ZkCqtaE5A6FSWAhtLryif3ZZWY9OgF0J/viOZNcsgArt5xKDRIBu5jOOHR4mkAAAA"
  },
  "projects/wheat-monument-1": {
    "src": "/media/projects/wheat-monument-1.webp",
    "width": 421,
    "height": 281,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAsAA4BaJbACdADPElNZAAD8fp0Yug81znU8u2HTahVVLJB//Q3ZYE45xDBlnes/r/LIhvhxfe7ZqCRAAA=="
  },
  "projects/wheat-monument-2": {
    "src": "/media/projects/wheat-monument-2.webp",
    "width": 162,
    "height": 216,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoMABAAA4BaJZQCdIExE5fVM5j5AAD+tTQxtyGNdGYxadOcajt8isG2ICOq18a8Fvph7/kg/3fB8wbmJhL+vjOO099YdUb/pO7AQAAA"
  },
  "projects/wheat-monument-3": {
    "src": "/media/projects/wheat-monument-3.webp",
    "width": 162,
    "height": 216,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMABAAA4BaJZQCdAEDffYedhRkAP7ma8B9jky7Gd/iQw1NZWbO3+0tyyolRrIeKb8GUZHBjuopkjWCuVuOrdU6fsFAZRZU5Bi6F6YPAAA="
  },
  "services/cnc-bending-1": {
    "src": "/media/services/cnc-bending-1.webp",
    "width": 295,
    "height": 197,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAsAA4BaJYwCdH8AF1rR+6igAP70kMItCVTLshoc5bWHxEBBbHe6DFPM/cknbqL4DOUgpg5f79KvnGvW/chqQRVvR/6AAAA="
  },
  "services/cnc-bending-2": {
    "src": "/media/services/cnc-bending-2.webp",
    "width": 291,
    "height": 194,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJQBdgBjeKbvexuKAAP2QBLVXebqHjXqGJ+HtjYOWE6PUgrdZlYhbB6uP1wscJ27Co52MSDLcTcKSVWWUNb2urQOTl6Rh7w9Rpo17RAvV6BNYAAA="
  },
  "services/cnc-bending-3": {
    "src": "/media/services/cnc-bending-3.webp",
    "width": 209,
    "height": 209,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQAgCdASoQABAAA4BaJQBYdsYxrHuGTFegAOJ5j2tk8Cx3Vo+KvAXJ1dEQl+VlIPo32WXKs6ZnSDMKBzKvsPfiO7tlTDRtOYOgd5KHCGLQ+POKcc7U6B/6uF7Z/unP1WL97CtM5bHHBspfCEhqTaiygAA="
  },
  "services/engraving-nameplates": {
    "src": "/media/services/engraving-nameplates.webp",
    "width": 262,
    "height": 465,
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAABwAQCdASoJABAAA4BaJZwAAYefyAD+TRed5/uV6fhgi18AjReC9VOpWwAAAA=="
  },
  "services/engraving-rotary": {
    "src": "/media/services/engraving-rotary.webp",
    "width": 285,
    "height": 155,
    "blurDataURL": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSEwAAAART6AmANA0SAM+h7lGREAl/jhcNxjFtt3kJaHJyA4DCIiJPzhgz+rpoPP0pmiI6P8EoHEnyQE4JWkCjmzE9haiilMqcE5azcwjLg45VlA4IEYAAACwAQCdASoQAAkAA4BaJaQAApNQn/AAAP7Lpvmj7Rd1CA384mniWLvo3tYMz03LTC7mRQPVT8xEjLZJTVt3ijeRhFRPgAAA"
  },
  "services/engraving-wood": {
    "src": "/media/services/engraving-wood.webp",
    "width": 172,
    "height": 143,
    "blurDataURL": "data:image/webp;base64,UklGRvAAAABXRUJQVlA4WAoAAAAQAAAADwAADAAAQUxQSFkAAAART6CgbSM3dxz2vnsAHxEB0/zw+yMwDQC2SdcBZRyAxZIH2OMEHLYSB7KOWnb+TX6I6P8EiDIV5OUI+4ZW2kJ7RNwOnB4kHTMz+cosjCeCoXZxEqgzAIC2kwBWUDggcAAAAPABAJ0BKhAADQADgFolkAJ0Bi311k1SAAD+P8Lc0op6jgmLcjgoL/+8JUyJp9dcrQgtFA3F3CeniDtlws69mxRR+U4Udq90A6U7VYaSAL1MA946wiPJLMkCCP37yFQ7bFqHeA8E4SP8JZPo0EwcqAA="
  },
  "services/fabrication-cut-sheets": {
    "src": "/media/services/fabrication-cut-sheets.webp",
    "width": 173,
    "height": 230,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMABAAA4BaJZACdAEKUEoGpj8AAOJWaPrj9MjKeCEnfh5fVUlGxvm395rmOPHD2MT70d4HIYwfKfWISJBK5OKmMN6ZhnOYxykgixZHgAA="
  },
  "services/fabrication-grinding": {
    "src": "/media/services/fabrication-grinding.webp",
    "width": 352,
    "height": 235,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAsAA4BaJbACdACpAkYAAP7s2I2tapdhy9GOVfh7qddef5bZmFis7sJDU6LMZJZPolpWkqOmcKy2R3Z+7kLdJuKbK0zEaemO3lcPsAA="
  },
  "services/fabrication-laser-welding": {
    "src": "/media/services/fabrication-laser-welding.webp",
    "width": 347,
    "height": 232,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJZwCw7DL9vZ2leagAP7pX786c0qFXEoSPrWOPcr+p9L2o/HiUUs5MD3+X4eyuBkIv/TLKCqL9NCngsClEa/BueztFVFEeTw96Ylm1QaNbi02AAA="
  },
  "services/fabrication-perforated-beams": {
    "src": "/media/services/fabrication-perforated-beams.webp",
    "width": 169,
    "height": 146,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAQCdASoQAA4AA4BaJZwAApbrKYAA+MX0OSK2utcBvYVFFFThr287ulVowficjLpxfbqj2e9jh1hNA5maIugzuRK+HcfMAuFRIND1p1kAAA=="
  },
  "services/fabrication-welding": {
    "src": "/media/services/fabrication-welding.webp",
    "width": 314,
    "height": 261,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAA0AA4BaJYwAAn28IG9l/04AAP7eAkcYUTn1SXSB2qV61JW2a5mfLwBmMrKyzkP0Gfj/8uBGoadIS5Lz2XMxW2WlQxo39ihQ/zqwplzjbD1n2dRcAAAA"
  },
  "services/fabrication-workshop": {
    "src": "/media/services/fabrication-workshop.webp",
    "width": 396,
    "height": 227,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAwAgCdASoQAAkAA4BaJZQCdAYuHlWWAlGffAD+6ACrw8gk3Sq58isv2M6VATrJ73RCuFYnKpnMeQQTY0OSKZz5ioIm0C2mZNAAAA=="
  },
  "services/scaffolding-1": {
    "src": "/media/services/scaffolding-1.webp",
    "width": 537,
    "height": 358,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAsAA4BaJYgCdAD0ZgsTxCAAAP7BhPQFiM6cPrqTHJPIBpBlsf/FrAcMrTc+MoMg6wk6eUtoosCIksrdfI/XjbDDtZQA"
  },
  "services/scaffolding-2": {
    "src": "/media/services/scaffolding-2.webp",
    "width": 538,
    "height": 359,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAsAA4BaJQBOgBdA7i3hjYAA/I5GiWNraUH5MqAVue61tKQch22HJKon+ko8ZCVsZGIktuNXZVWxKPt9yGSQAAA="
  },
  "services/scaffolding-3": {
    "src": "/media/services/scaffolding-3.webp",
    "width": 431,
    "height": 212,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAgAA4BaJZwAAn+1SOMBAAD8zzti1mkaH/osfARMj2zc7pxC52Ajn1rk404aRO54QAAA"
  },
  "services/scaffolding-4": {
    "src": "/media/services/scaffolding-4.webp",
    "width": 455,
    "height": 256,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJQBOgBkljF/gAMyjwdmZThZb+J50haaEn6RJBCyZATk88nPuDkotH7iDeaNK8tU7OfJb1ayEUnaLcxBLcAAA"
  },
  "services/scaffolding-5": {
    "src": "/media/services/scaffolding-5.webp",
    "width": 209,
    "height": 254,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoNABAAA4BaJQBOgCFsjt5Jw06IMAD+14iGn/K5N+XSNc+FccFXerXWL5eHqrF67J5kOdqPtae7uTs73Ou0k/yUKtlyr3sqAAA="
  },
  "services/scaffolding-props": {
    "src": "/media/services/scaffolding-props.webp",
    "width": 231,
    "height": 209,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoQAA4AA4BaJbACdADpIHYnFnTQAAD7IE/Kkr2qbE9C2zZD9/2blSk/GLaN5M4vJl6YNy92L0HqhY4/8LSmW+o456aHF5hk62PSIzX1vHeyfEjAWt3HDPOqyCMgEZSWsAA="
  },
  "services/steel-structures-1": {
    "src": "/media/services/steel-structures-1.webp",
    "width": 446,
    "height": 228,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAgAA4BaJZwAAxf/J9vtnwAA/vVJw9g10J6psmAjxmiv+wJL5yH/jZrvC7zfTVlLJezABZAAAA=="
  },
  "services/steel-structures-2": {
    "src": "/media/services/steel-structures-2.webp",
    "width": 405,
    "height": 270,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQAgCdASoQAAsAA4BaJYwCdIExGBpv4qDA5oAA/luXzORS0DMYXl7/bYytSe6QO+T1igSfqMWksWgi/iiLrGScQkxPjpkZAAA="
  },
  "services/steel-structures-3": {
    "src": "/media/services/steel-structures-3.webp",
    "width": 228,
    "height": 228,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwAgCdASoQABAAA4BaJQBOgMWWztk4P2H7PDYQAM45OwlRbUy4sXbdv1cpaAvzsBpsIno5EK4C8PIo2d7N2TvdL3d2ieDWv8M4JN1r2SWfS6WnmEV1iWmiHM39618cTuLkA7B+QJ7M5K0CcAxClEnL8GeZImPKAAA="
  },
  "services/steel-structures-4": {
    "src": "/media/services/steel-structures-4.webp",
    "width": 367,
    "height": 206,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkAA4BaJbACdAEOJFcbkAD+zeVxOgDG0RxuFMeUU9IcUNa9hzk5NVNxGCl+Z+8RE9rxz3OIAA=="
  },
  "site/laser-head": {
    "src": "/media/site/laser-head.webp",
    "width": 329,
    "height": 241,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJbACdAEDoIvXwYYAAP7dWgmvbzs+mVwvR7adf3u9JYcnQga3/LDo5Q4nEliQxPkZsmZzlWzSs4UgSv8sz6tbiCrJWUXBZkKGaAAA"
  },
  "site/laser-sparks": {
    "src": "/media/site/laser-sparks.webp",
    "width": 766,
    "height": 511,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAsAA4BaJaACdAEK6qTNFAD+98cjlxvusLDEReNVTLIezmwgUJgAFiIfE8nKDgYMVBUL/JDUvW36BkziXOdS2WZPH6GDEfdDvWsWjmDRAAAA"
  },
  "site/riyadh-night": {
    "src": "/media/site/riyadh-night.webp",
    "width": 2029,
    "height": 1348,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAsAA4BaJbACdGuAAsteYBu3mAD+4vFRqE+6GQICjP0p057U0/9FgC1krWjEux0bwD5HXzubZ1n8TkK0Bj71UTQNZbGenuPVgAAA"
  },
  "site/scaffold-silhouettes": {
    "src": "/media/site/scaffold-silhouettes.webp",
    "width": 411,
    "height": 278,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsAA4BaJbACdAEPABjRCWlwAP6qD29m6iwFpDP03o+yCLTFJYoF+qQOtLlO1BRhsPD5QoMPGaySxjnlefHE6WifXP5g4aqeWmDonpu4AA=="
  },
  "site/site-engineers": {
    "src": "/media/site/site-engineers.webp",
    "width": 1035,
    "height": 690,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAsAA4BaJQBOgCIAcwygnAIAAP7hIIzPQg6qv4K7iz9r+RoKjHsFUiNh9J3yFPhkAtrWVloH9OkZ8pl8Z09M/e29mDnWvRdjqU2z7bmHnOAA"
  },
  "site/steel-beams-hall": {
    "src": "/media/site/steel-beams-hall.webp",
    "width": 888,
    "height": 593,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAsAA4BaJZgCdADhiklO0c8rCAD+4NHvIuUo2G8ZZwDoMA4a7kvf9FLE9K8uXFXMwjpJkwFf3/UGFR8vFLoGO9fll3yZDpaQdUxg7fqAAA=="
  },
  "site/steel-frame-dusk": {
    "src": "/media/site/steel-frame-dusk.webp",
    "width": 490,
    "height": 321,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA4BaJbACdAD5/pW7JtxAAP0ZkXPTPTUrFDnmHJUnsBm5TAvmPcXq3qO1kp3C8Pqzu5HSCH6Xa/fJ4nqW4hm35YDqNzM0AAAA"
  },
  "site/welder-sparks": {
    "src": "/media/site/welder-sparks.webp",
    "width": 349,
    "height": 233,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAsAA4BaJbACdAC70pItGAAA9HQl6Wxnfaa3aa6KmH31xp/fjOuAjUWmbv9UH8vlZWs5qPCiPxHpaxsMb9hWtEJS6Q3C9ItB06gNmSDdtzGbc2J8Co6HMaAAAA=="
  }
} as const;

export type MediaId = keyof typeof mediaRegistry;
